Configuration
eleven-labs/blog.eleven-labs.com pull request #1138
Opened 2024-07-19 09:54 UTC by Yuhiba

added the author elemarchand and set up metadata for the article.

2024-07-19 14:16 UTC, lepiaf requested changes

2024-07-19 14:16 UTC, lepiaf commented on _authors/elemarchand.md
> +linkedin: https://www.linkedin.com/in/elodie-lemarchand-scrum-coach/
c'est juste le nom, pas besoin de mettre l'url complète.

```suggestion
linkedin: elodie-lemarchand-scrum-coach
```

2024-07-19 14:20 UTC, lepiaf commented on _authors/elemarchand.md
> +username: eLemarchand
je me demande si la valeur du username doit être le même que celui de la photo.

2024-07-22 10:23 UTC, lepiaf approved these changes

2024-07-22 15:42 UTC, Shad-Z approved these changes

2024-07-22 15:47 UTC, merged