Update blog dependencies
eleven-labs/blog.eleven-labs.com pull request #786
Opened 2020-12-02 23:36 UTC by Vik-Th0r

2020-12-03 14:53 UTC, VEBERArnaud requested changes
some changes requested, but the overall update process looks goof 😉

2020-12-03 14:53 UTC, VEBERArnaud commented on _algolia.yml
> +    extensions_to_index:
```suggestion
    files_to_exclude:
```

based on migration guide https://community.algolia.com/jekyll-algolia/migration-guide.html#options

> excluded_files has been renamed to files_to_exclude

2020-12-03 14:53 UTC, VEBERArnaud commented on _config.yml
> +    - jekyll-algolia
```suggestion
```

from migration guide https://community.algolia.com/jekyll-algolia/migration-guide.html#renaming

> Note that you no longer need to add the plugin to the list of plugins in your _config.yml, this is now taken care of at the Gemfile level. The other important change is that the new version requires at least Ruby 2.3 and Jekyll 3.6 to work.

2020-12-04 15:40 UTC, guillemcanal commented on Gemfile.lock
> +  remote: https://github.com/Vik-Th0r/amp-jekyll
Pas la bonne remote il me semble

2020-12-04 15:53 UTC, snroki commented on Gemfile.lock
> +  remote: https://github.com/Vik-Th0r/jekyll-multiple-languages-plugin
pareil le remote devrait être le repo eleven non ?

2020-12-09 17:06 UTC, VEBERArnaud approved these changes
LGTM

2020-12-09 17:06 UTC, merged