Feat tagging multilang
eleven-labs/blog.eleven-labs.com pull request #787
Opened 2020-12-10 15:58 UTC by Vik-Th0r

ajouter les tags sur le blog
rendre accessible touts les articles lié à un tag
rendre ces pages accessible via un flux rss
gérer ce process dans les langues disponibles

2020-12-10 18:39 UTC, ElevenWilson commented
2769 words might be misspelled, please check them: aa, aandre, abd, Aboaf, Abramov, Abramov's, AbstractAdapter, AbstractController, accesseurs, AccountCanTransferMoney, ack, Ack, ACK, ACL, AComponent, acté, ActionTypes, activationCommands, addChild, addDecorator, addDoneButtonOnKeyboard, addEventListener, addGestureRecognizer, addkey, addListener, addon, Addon, addonlist, addons, Addons, addPlugin, addScore, addSelect, adduser, adminpass, ADR, AES, AESGCM, afup, Afup, AFUP, Aga, aggration, Agilbee, agileparis, agiletour, agiletourparis, AgileTourParis, agilite, Agnès, ahk, airbnb, Airbnb, ajax, Akamai, Alamofire, AlamofireImage, alertMsg, Alexandre, algo, allSettled, ALors, alorscettearticle, amateure, Amélie, amelieboucher, Amongst, amoutte, amq, amqp, AMQP, AMQPConnection, amqplib, AMQPMessage, Anaïs, analytics, Andreosso, androïd, angularCLI, AngularCLI, AngularJs, AngularJS, AnnotationRegistry, anotherfe, ansur, AOT, APi, ApiBundle, ApiManager, APIs, apk, apks, apm, Apns, APNs, apollo, apolloJS, ApolloJS, apparait, apparaitre, Appbundle, AppBundle, AppCache, AppCompatActivity, AppData, AppEngine, Appfile, AppKernel, appli, applicationId, applicative, applicatives, applis, applyMiddleware, AprilKing, aps, ARANGO, args, ArgvInput, arn, ARN, Arnaud, ArrayCollection, Arreter, ArticleControllerTest, ArticleListener, ArticleRepository, ArticleService, asc, asciinema, assertContains, assertEquals, assertInstanceOf, assertNotEmpty, assertTrue, Assetic, ast, AST, astonautes, AstronautController, AstronauteTests, astronautsKey, astronautsRepository, AstronautsRepository, async, Async, Asynctask, attachEvent, attemptReset, attrName, attrs, Aubervilliers, audras, Audras, auteure, auth, AuthGuard, AuthHttp, authHttpServiceFactory, autocomplete, autocomplétion, autoconfigure, AutoHotKey, autoload, autoloaded, autoloader, autoloadés, autorized, autosquash, autowiring, AUTOWIRING, AvZNc, aws, Aws, AWS, axios, babelrc, BabylonJS, backend, Backend, BACKEND, backends, BackOffice, BackstopJs, backupGlobals, backupStaticAttributes, banniere, barAction, barButtonSystemItem, Barrista, barStyle, BaseBuilder, BaseClient, BaseConnection, BaseDocumentRepository, BaseExpr, baseurl, baseUrl, baseURL, BaseWebTestCase, bashrc, basicauth, baz, BDD, Bedford, beginTransaction, behat, Behat, BehatHTMLFormatter, BehatHTMLFormatterExtension, Belin, benevolat, benoit, beoneself, bétises, Bidelman, bidimensionnelles, bidirectionnalité, bientot, BigData, bindActionCreators, bindé, bindée, bindées, binôme, binômes, Bisounours, Bistri, BitBucket, Bithound, blackslash, bling, bloquage, bluetooth, bolognaise, bool, Bool, boolean, booleans, bootable, booter, bootloader, Bootloader, bordelique, botnet, Bouissou, BouteilleTest, brainstormer, Broutin, BrowserRouter, BSOD, BuildConfig, buildez, BuildFields, buildParameters, buildtype, buildType, buildTypes, BuildTypes, bundleName, bundler, byKeyPath, byProperty, cacheAction, cacheApp, cacheControl, cacheDir, cacheFirst, CacheInterface, CacheItem, callApi, callWebService, canActivate, caniuse, CannotPublishException, captainjojo, captainJojo, CarDetail, CarList, Carriou, Casabianca, CCMBenchmark, cd, CDD, celà, Cepedant, cer, certbot, Certbot, certonly, certSigningRequest, chaine, chainer, changeLabel, changeLanguage, changelog, chapo, charles, charset, chatbot, checkAndIncrease, checkCredentials, checkez, Cheric, ChericExampleBundle, Chet, chiffée, Chignet, ChildComponent, choo, choosen, Christophe, chronophage, ciblée, circuitBreaker, CircuitBreaker, CircuitBreakerEvent, CircuitBreakerService, cksum, ClassLoader, classname, className, cleé, cli, Cli, CLI, Clickjacking, clientId, clipRect, cliquant, cliquer, Cliquer, cliquez, Cliquez, cloné, Clonez, CLose, ClosureExpressionBuilder, Clycks, ClycksBundle, ClycksClycksBundleController, ClycksController, cmd, Cmd, CNIL, coachs, Cocoapods, codeception, Codeception, Codelab, codelabs, Codelabs, CodeLabs, Codeship, codesigning, codestyling, Coffeescript, CoffeeScript, cogren, colorScheme, combineReducers, commandTester, CommandTester, commencant, commiter, CommitStrip, CommonJS, Communauty, compactée, complétement, complile, componentDidMount, componentDidUpdate, componentWillUnmount, ComposantEnfant, ComposantParent, Composieux, CompositeDisposable, concat, config, Config, CONFIG, configugarion, ConfigurationInterface, configurator, configureStore, configureUserInteractions, confs, connait, connaitre, conntrack, const, constraintlayout, ConstraintLayout, constraste, ContainerAware, ContainerAwareCommand, ContainerInterface, contentType, contextapi, ContextApi, ContextAPI, contributeur, controle, controlleur, convertErrorsToExceptions, convertNoticesToExceptions, convertWarningsToExceptions, coords, CoP, Copresence, Cordova, coredata, coreData, CoreData, coroutine, CoroutineLifeCycleListener, coroutines, correctServerQueryString, corresponddant, CouldNotCopyFileException, CounterActions, countFailure, countryOfOrigin, courrant, CQRS, createAnnotationMetadataConfiguration, createClient, createComponent, createContext, createdAt, createDir, createDraft, createElement, createFactory, createFromGlobals, createItem, createKernel, createQuery, createQueryBuilder, createSignalingChannel, createStore, creer, Creer, CRLF, cron, CRON, Crons, croped, crowdsourcer, cryptage, cryptanalysis, cryptographic, Cryptographic, cryptographiques, CSP, CSR, css, CSS, CSV, ctags, CTags, cto, CTO, ctrl, Ctrl, ctstate, cURL, customisés, CVAA, cy, Cybersécurité, da, d'a, d’Abstract, d'accélerer, d'acceptances, D'add, d'addon, d’Agilité, d’Amazon, damien, d'AMP, d'android, d'Android, d’Android, d'Angular, Dan's, d'ansible, d'Apache, d'API, d’API, d'Apollo, d'ApolloJS, d'app, Darkmira, Darricau, Dasini, DASINI, d'assets, DataFixtures, dataIdFromObject, dataItem, DataLayer, dataLayout, datamatrix, dataset, DataSource, dataType, datetime, DateTime, d'Atom, d'auth, dauthentification, d'autocomplétion, d'autoload, d'autoscalling, d’AWS, DBAL, dbd, DDD, ddos, DDR, débogage, debogue, Deboguer, débogueur, d’ebooks, débrief, débriefing, debuggables, débugger, débuggeur, decache, décacher, d’ECMAscript, decrement, Decrement, DECREMENT, décrouvrons, dedeparisg, d'Edward, defaultConfig, DefaultController, defaultNS, défnir, déja, Delécolle, deleteDir, DeleteRealmIfMigrationNeeded, d'Eleven, d’Eleven, Delevery, Delrieu, d'emails, d’Emmanuelle, démo, DemoMyBundle, démos, d'émulateur, d'encrypter, Denos, dependancies, DependencyInjection, dépilement, déployables, dépot, Derussé, DERUSSÉ, d'ES, désalloué, DeSandro, Desbenoit, desc, descendEnBas, descripteurs, désélectionner, désérialisation, deserialize, désinscrites, désinstallation, désinstallé, Désinstaller, d'Eslint, dessend, destinaitaire, destructuring, désuette, desynchronization, detabinator, deuxieme, dev, Dev, dév, devbridge, developper, développeuse, développeuses, developpez, devfest, DevFest, DevFestNantes, devops, DevOps, devs, DevTools, d'éxecuter, d'éxécuter, d'execution, d'Expérience, d'export, dfce, d'helpers, d'HTTP, d’HTTP, DialoFlow, dialogflow, DialogFlow, d’IBM, d’ID, d'identifiant, didFailToRegisterForRemoteNotificationsWithError, didFinishLaunchingWithOptions, didReceiveRemoteNotification, didRegisterForRemoteNotificationsWithDeviceToken, d’ile, d’implémentation, d'implémentations, d'import, d’inbound, d’Infrastructure, d'instancier, d'integration, d’internet, d'Internet, d’Internet, d’interopérabilité, d'intéropérabilité, d’IOS, diposez, dir, dirname, disableOriginalConstructor, dispo, DistributionBundle, distros, DivisionByZeroException, Djavan, DLK, DLX, DMX, dns, DNS, d’Objective, docarticle, Dockerfile, dockerfiles, DockerHub, dockerisées, dockerremotephpdebugingexample, DockerRemotePhpDebugingExample, d'OCR, DocsPage, DoctrineBundle, DoctrineExtensionsBundle, DoctrineFixturesBundle, DocumentManager, documentName, DocumentRepository, d'ODM, d'Olivier, domotique, domotiques, doneButtonAction, doneToolbar, donut, Donut, d’opcode, d'OpenPGP, d'OpenSSL, doRequest, do [...]

2020-12-11 14:30 UTC, ElevenWilson commented
2769 words might be misspelled, please check them: aa, aandre, abd, Aboaf, Abramov, Abramov's, AbstractAdapter, AbstractController, accesseurs, AccountCanTransferMoney, ack, Ack, ACK, ACL, AComponent, acté, ActionTypes, activationCommands, addChild, addDecorator, addDoneButtonOnKeyboard, addEventListener, addGestureRecognizer, addkey, addListener, addon, Addon, addonlist, addons, Addons, addPlugin, addScore, addSelect, adduser, adminpass, ADR, AES, AESGCM, afup, Afup, AFUP, Aga, aggration, Agilbee, agileparis, agiletour, agiletourparis, AgileTourParis, agilite, Agnès, ahk, airbnb, Airbnb, ajax, Akamai, Alamofire, AlamofireImage, alertMsg, Alexandre, algo, allSettled, ALors, alorscettearticle, amateure, Amélie, amelieboucher, Amongst, amoutte, amq, amqp, AMQP, AMQPConnection, amqplib, AMQPMessage, Anaïs, analytics, Andreosso, androïd, angularCLI, AngularCLI, AngularJs, AngularJS, AnnotationRegistry, anotherfe, ansur, AOT, APi, ApiBundle, ApiManager, APIs, apk, apks, apm, Apns, APNs, apollo, apolloJS, ApolloJS, apparait, apparaitre, Appbundle, AppBundle, AppCache, AppCompatActivity, AppData, AppEngine, Appfile, AppKernel, appli, applicationId, applicative, applicatives, applis, applyMiddleware, AprilKing, aps, ARANGO, args, ArgvInput, arn, ARN, Arnaud, ArrayCollection, Arreter, ArticleControllerTest, ArticleListener, ArticleRepository, ArticleService, asc, asciinema, assertContains, assertEquals, assertInstanceOf, assertNotEmpty, assertTrue, Assetic, ast, AST, astonautes, AstronautController, AstronauteTests, astronautsKey, astronautsRepository, AstronautsRepository, async, Async, Asynctask, attachEvent, attemptReset, attrName, attrs, Aubervilliers, audras, Audras, auteure, auth, AuthGuard, AuthHttp, authHttpServiceFactory, autocomplete, autocomplétion, autoconfigure, AutoHotKey, autoload, autoloaded, autoloader, autoloadés, autorized, autosquash, autowiring, AUTOWIRING, AvZNc, aws, Aws, AWS, axios, babelrc, BabylonJS, backend, Backend, BACKEND, backends, BackOffice, BackstopJs, backupGlobals, backupStaticAttributes, banniere, barAction, barButtonSystemItem, Barrista, barStyle, BaseBuilder, BaseClient, BaseConnection, BaseDocumentRepository, BaseExpr, baseurl, baseUrl, baseURL, BaseWebTestCase, bashrc, basicauth, baz, BDD, Bedford, beginTransaction, behat, Behat, BehatHTMLFormatter, BehatHTMLFormatterExtension, Belin, benevolat, benoit, beoneself, bétises, Bidelman, bidimensionnelles, bidirectionnalité, bientot, BigData, bindActionCreators, bindé, bindée, bindées, binôme, binômes, Bisounours, Bistri, BitBucket, Bithound, blackslash, bling, bloquage, bluetooth, bolognaise, bool, Bool, boolean, booleans, bootable, booter, bootloader, Bootloader, bordelique, botnet, Bouissou, BouteilleTest, brainstormer, Broutin, BrowserRouter, BSOD, BuildConfig, buildez, BuildFields, buildParameters, buildtype, buildType, buildTypes, BuildTypes, bundleName, bundler, byKeyPath, byProperty, cacheAction, cacheApp, cacheControl, cacheDir, cacheFirst, CacheInterface, CacheItem, callApi, callWebService, canActivate, caniuse, CannotPublishException, captainjojo, captainJojo, CarDetail, CarList, Carriou, Casabianca, CCMBenchmark, cd, CDD, celà, Cepedant, cer, certbot, Certbot, certonly, certSigningRequest, chaine, chainer, changeLabel, changeLanguage, changelog, chapo, charles, charset, chatbot, checkAndIncrease, checkCredentials, checkez, Cheric, ChericExampleBundle, Chet, chiffée, Chignet, ChildComponent, choo, choosen, Christophe, chronophage, ciblée, circuitBreaker, CircuitBreaker, CircuitBreakerEvent, CircuitBreakerService, cksum, ClassLoader, classname, className, cleé, cli, Cli, CLI, Clickjacking, clientId, clipRect, cliquant, cliquer, Cliquer, cliquez, Cliquez, cloné, Clonez, CLose, ClosureExpressionBuilder, Clycks, ClycksBundle, ClycksClycksBundleController, ClycksController, cmd, Cmd, CNIL, coachs, Cocoapods, codeception, Codeception, Codelab, codelabs, Codelabs, CodeLabs, Codeship, codesigning, codestyling, Coffeescript, CoffeeScript, cogren, colorScheme, combineReducers, commandTester, CommandTester, commencant, commiter, CommitStrip, CommonJS, Communauty, compactée, complétement, complile, componentDidMount, componentDidUpdate, componentWillUnmount, ComposantEnfant, ComposantParent, Composieux, CompositeDisposable, concat, config, Config, CONFIG, configugarion, ConfigurationInterface, configurator, configureStore, configureUserInteractions, confs, connait, connaitre, conntrack, const, constraintlayout, ConstraintLayout, constraste, ContainerAware, ContainerAwareCommand, ContainerInterface, contentType, contextapi, ContextApi, ContextAPI, contributeur, controle, controlleur, convertErrorsToExceptions, convertNoticesToExceptions, convertWarningsToExceptions, coords, CoP, Copresence, Cordova, coredata, coreData, CoreData, coroutine, CoroutineLifeCycleListener, coroutines, correctServerQueryString, corresponddant, CouldNotCopyFileException, CounterActions, countFailure, countryOfOrigin, courrant, CQRS, createAnnotationMetadataConfiguration, createClient, createComponent, createContext, createdAt, createDir, createDraft, createElement, createFactory, createFromGlobals, createItem, createKernel, createQuery, createQueryBuilder, createSignalingChannel, createStore, creer, Creer, CRLF, cron, CRON, Crons, croped, crowdsourcer, cryptage, cryptanalysis, cryptographic, Cryptographic, cryptographiques, CSP, CSR, css, CSS, CSV, ctags, CTags, cto, CTO, ctrl, Ctrl, ctstate, cURL, customisés, CVAA, cy, Cybersécurité, da, d'a, d’Abstract, d'accélerer, d'acceptances, D'add, d'addon, d’Agilité, d’Amazon, damien, d'AMP, d'android, d'Android, d’Android, d'Angular, Dan's, d'ansible, d'Apache, d'API, d’API, d'Apollo, d'ApolloJS, d'app, Darkmira, Darricau, Dasini, DASINI, d'assets, DataFixtures, dataIdFromObject, dataItem, DataLayer, dataLayout, datamatrix, dataset, DataSource, dataType, datetime, DateTime, d'Atom, d'auth, dauthentification, d'autocomplétion, d'autoload, d'autoscalling, d’AWS, DBAL, dbd, DDD, ddos, DDR, débogage, debogue, Deboguer, débogueur, d’ebooks, débrief, débriefing, debuggables, débugger, débuggeur, decache, décacher, d’ECMAscript, decrement, Decrement, DECREMENT, décrouvrons, dedeparisg, d'Edward, defaultConfig, DefaultController, defaultNS, défnir, déja, Delécolle, deleteDir, DeleteRealmIfMigrationNeeded, d'Eleven, d’Eleven, Delevery, Delrieu, d'emails, d’Emmanuelle, démo, DemoMyBundle, démos, d'émulateur, d'encrypter, Denos, dependancies, DependencyInjection, dépilement, déployables, dépot, Derussé, DERUSSÉ, d'ES, désalloué, DeSandro, Desbenoit, desc, descendEnBas, descripteurs, désélectionner, désérialisation, deserialize, désinscrites, désinstallation, désinstallé, Désinstaller, d'Eslint, dessend, destinaitaire, destructuring, désuette, desynchronization, detabinator, deuxieme, dev, Dev, dév, devbridge, developper, développeuse, développeuses, developpez, devfest, DevFest, DevFestNantes, devops, DevOps, devs, DevTools, d'éxecuter, d'éxécuter, d'execution, d'Expérience, d'export, dfce, d'helpers, d'HTTP, d’HTTP, DialoFlow, dialogflow, DialogFlow, d’IBM, d’ID, d'identifiant, didFailToRegisterForRemoteNotificationsWithError, didFinishLaunchingWithOptions, didReceiveRemoteNotification, didRegisterForRemoteNotificationsWithDeviceToken, d’ile, d’implémentation, d'implémentations, d'import, d’inbound, d’Infrastructure, d'instancier, d'integration, d’internet, d'Internet, d’Internet, d’interopérabilité, d'intéropérabilité, d’IOS, diposez, dir, dirname, disableOriginalConstructor, dispo, DistributionBundle, distros, DivisionByZeroException, Djavan, DLK, DLX, DMX, dns, DNS, d’Objective, docarticle, Dockerfile, dockerfiles, DockerHub, dockerisées, dockerremotephpdebugingexample, DockerRemotePhpDebugingExample, d'OCR, DocsPage, DoctrineBundle, DoctrineExtensionsBundle, DoctrineFixturesBundle, DocumentManager, documentName, DocumentRepository, d'ODM, d'Olivier, domotique, domotiques, doneButtonAction, doneToolbar, donut, Donut, d’opcode, d'OpenPGP, d'OpenSSL, doRequest, do [...]

2020-12-14 14:41 UTC, ElevenWilson commented
2769 words might be misspelled, please check them: aa, aandre, abd, Aboaf, Abramov, Abramov's, AbstractAdapter, AbstractController, accesseurs, AccountCanTransferMoney, ack, Ack, ACK, ACL, AComponent, acté, ActionTypes, activationCommands, addChild, addDecorator, addDoneButtonOnKeyboard, addEventListener, addGestureRecognizer, addkey, addListener, addon, Addon, addonlist, addons, Addons, addPlugin, addScore, addSelect, adduser, adminpass, ADR, AES, AESGCM, afup, Afup, AFUP, Aga, aggration, Agilbee, agileparis, agiletour, agiletourparis, AgileTourParis, agilite, Agnès, ahk, airbnb, Airbnb, ajax, Akamai, Alamofire, AlamofireImage, alertMsg, Alexandre, algo, allSettled, ALors, alorscettearticle, amateure, Amélie, amelieboucher, Amongst, amoutte, amq, amqp, AMQP, AMQPConnection, amqplib, AMQPMessage, Anaïs, analytics, Andreosso, androïd, angularCLI, AngularCLI, AngularJs, AngularJS, AnnotationRegistry, anotherfe, ansur, AOT, APi, ApiBundle, ApiManager, APIs, apk, apks, apm, Apns, APNs, apollo, apolloJS, ApolloJS, apparait, apparaitre, Appbundle, AppBundle, AppCache, AppCompatActivity, AppData, AppEngine, Appfile, AppKernel, appli, applicationId, applicative, applicatives, applis, applyMiddleware, AprilKing, aps, ARANGO, args, ArgvInput, arn, ARN, Arnaud, ArrayCollection, Arreter, ArticleControllerTest, ArticleListener, ArticleRepository, ArticleService, asc, asciinema, assertContains, assertEquals, assertInstanceOf, assertNotEmpty, assertTrue, Assetic, ast, AST, astonautes, AstronautController, AstronauteTests, astronautsKey, astronautsRepository, AstronautsRepository, async, Async, Asynctask, attachEvent, attemptReset, attrName, attrs, Aubervilliers, audras, Audras, auteure, auth, AuthGuard, AuthHttp, authHttpServiceFactory, autocomplete, autocomplétion, autoconfigure, AutoHotKey, autoload, autoloaded, autoloader, autoloadés, autorized, autosquash, autowiring, AUTOWIRING, AvZNc, aws, Aws, AWS, axios, babelrc, BabylonJS, backend, Backend, BACKEND, backends, BackOffice, BackstopJs, backupGlobals, backupStaticAttributes, banniere, barAction, barButtonSystemItem, Barrista, barStyle, BaseBuilder, BaseClient, BaseConnection, BaseDocumentRepository, BaseExpr, baseurl, baseUrl, baseURL, BaseWebTestCase, bashrc, basicauth, baz, BDD, Bedford, beginTransaction, behat, Behat, BehatHTMLFormatter, BehatHTMLFormatterExtension, Belin, benevolat, benoit, beoneself, bétises, Bidelman, bidimensionnelles, bidirectionnalité, bientot, BigData, bindActionCreators, bindé, bindée, bindées, binôme, binômes, Bisounours, Bistri, BitBucket, Bithound, blackslash, bling, bloquage, bluetooth, bolognaise, bool, Bool, boolean, booleans, bootable, booter, bootloader, Bootloader, bordelique, botnet, Bouissou, BouteilleTest, brainstormer, Broutin, BrowserRouter, BSOD, BuildConfig, buildez, BuildFields, buildParameters, buildtype, buildType, buildTypes, BuildTypes, bundleName, bundler, byKeyPath, byProperty, cacheAction, cacheApp, cacheControl, cacheDir, cacheFirst, CacheInterface, CacheItem, callApi, callWebService, canActivate, caniuse, CannotPublishException, captainjojo, captainJojo, CarDetail, CarList, Carriou, Casabianca, CCMBenchmark, cd, CDD, celà, Cepedant, cer, certbot, Certbot, certonly, certSigningRequest, chaine, chainer, changeLabel, changeLanguage, changelog, chapo, charles, charset, chatbot, checkAndIncrease, checkCredentials, checkez, Cheric, ChericExampleBundle, Chet, chiffée, Chignet, ChildComponent, choo, choosen, Christophe, chronophage, ciblée, circuitBreaker, CircuitBreaker, CircuitBreakerEvent, CircuitBreakerService, cksum, ClassLoader, classname, className, cleé, cli, Cli, CLI, Clickjacking, clientId, clipRect, cliquant, cliquer, Cliquer, cliquez, Cliquez, cloné, Clonez, CLose, ClosureExpressionBuilder, Clycks, ClycksBundle, ClycksClycksBundleController, ClycksController, cmd, Cmd, CNIL, coachs, Cocoapods, codeception, Codeception, Codelab, codelabs, Codelabs, CodeLabs, Codeship, codesigning, codestyling, Coffeescript, CoffeeScript, cogren, colorScheme, combineReducers, commandTester, CommandTester, commencant, commiter, CommitStrip, CommonJS, Communauty, compactée, complétement, complile, componentDidMount, componentDidUpdate, componentWillUnmount, ComposantEnfant, ComposantParent, Composieux, CompositeDisposable, concat, config, Config, CONFIG, configugarion, ConfigurationInterface, configurator, configureStore, configureUserInteractions, confs, connait, connaitre, conntrack, const, constraintlayout, ConstraintLayout, constraste, ContainerAware, ContainerAwareCommand, ContainerInterface, contentType, contextapi, ContextApi, ContextAPI, contributeur, controle, controlleur, convertErrorsToExceptions, convertNoticesToExceptions, convertWarningsToExceptions, coords, CoP, Copresence, Cordova, coredata, coreData, CoreData, coroutine, CoroutineLifeCycleListener, coroutines, correctServerQueryString, corresponddant, CouldNotCopyFileException, CounterActions, countFailure, countryOfOrigin, courrant, CQRS, createAnnotationMetadataConfiguration, createClient, createComponent, createContext, createdAt, createDir, createDraft, createElement, createFactory, createFromGlobals, createItem, createKernel, createQuery, createQueryBuilder, createSignalingChannel, createStore, creer, Creer, CRLF, cron, CRON, Crons, croped, crowdsourcer, cryptage, cryptanalysis, cryptographic, Cryptographic, cryptographiques, CSP, CSR, css, CSS, CSV, ctags, CTags, cto, CTO, ctrl, Ctrl, ctstate, cURL, customisés, CVAA, cy, Cybersécurité, da, d'a, d’Abstract, d'accélerer, d'acceptances, D'add, d'addon, d’Agilité, d’Amazon, damien, d'AMP, d'android, d'Android, d’Android, d'Angular, Dan's, d'ansible, d'Apache, d'API, d’API, d'Apollo, d'ApolloJS, d'app, Darkmira, Darricau, Dasini, DASINI, d'assets, DataFixtures, dataIdFromObject, dataItem, DataLayer, dataLayout, datamatrix, dataset, DataSource, dataType, datetime, DateTime, d'Atom, d'auth, dauthentification, d'autocomplétion, d'autoload, d'autoscalling, d’AWS, DBAL, dbd, DDD, ddos, DDR, débogage, debogue, Deboguer, débogueur, d’ebooks, débrief, débriefing, debuggables, débugger, débuggeur, decache, décacher, d’ECMAscript, decrement, Decrement, DECREMENT, décrouvrons, dedeparisg, d'Edward, defaultConfig, DefaultController, defaultNS, défnir, déja, Delécolle, deleteDir, DeleteRealmIfMigrationNeeded, d'Eleven, d’Eleven, Delevery, Delrieu, d'emails, d’Emmanuelle, démo, DemoMyBundle, démos, d'émulateur, d'encrypter, Denos, dependancies, DependencyInjection, dépilement, déployables, dépot, Derussé, DERUSSÉ, d'ES, désalloué, DeSandro, Desbenoit, desc, descendEnBas, descripteurs, désélectionner, désérialisation, deserialize, désinscrites, désinstallation, désinstallé, Désinstaller, d'Eslint, dessend, destinaitaire, destructuring, désuette, desynchronization, detabinator, deuxieme, dev, Dev, dév, devbridge, developper, développeuse, développeuses, developpez, devfest, DevFest, DevFestNantes, devops, DevOps, devs, DevTools, d'éxecuter, d'éxécuter, d'execution, d'Expérience, d'export, dfce, d'helpers, d'HTTP, d’HTTP, DialoFlow, dialogflow, DialogFlow, d’IBM, d’ID, d'identifiant, didFailToRegisterForRemoteNotificationsWithError, didFinishLaunchingWithOptions, didReceiveRemoteNotification, didRegisterForRemoteNotificationsWithDeviceToken, d’ile, d’implémentation, d'implémentations, d'import, d’inbound, d’Infrastructure, d'instancier, d'integration, d’internet, d'Internet, d’Internet, d’interopérabilité, d'intéropérabilité, d’IOS, diposez, dir, dirname, disableOriginalConstructor, dispo, DistributionBundle, distros, DivisionByZeroException, Djavan, DLK, DLX, DMX, dns, DNS, d’Objective, docarticle, Dockerfile, dockerfiles, DockerHub, dockerisées, dockerremotephpdebugingexample, DockerRemotePhpDebugingExample, d'OCR, DocsPage, DoctrineBundle, DoctrineExtensionsBundle, DoctrineFixturesBundle, DocumentManager, documentName, DocumentRepository, d'ODM, d'Olivier, domotique, domotiques, doneButtonAction, doneToolbar, donut, Donut, d’opcode, d'OpenPGP, d'OpenSSL, doRequest, do [...]

2020-12-29 13:53 UTC, ElevenWilson commented
2730 words might be misspelled, please check them: aa, aandre, abd, Aboaf, Abramov, Abramov's, AbstractAdapter, AbstractController, accesseurs, AccountCanTransferMoney, ack, Ack, ACK, ACL, AComponent, acté, ActionTypes, activationCommands, addChild, addDecorator, addDoneButtonOnKeyboard, addEventListener, addGestureRecognizer, addkey, addListener, addon, Addon, addonlist, addons, Addons, addPlugin, addScore, addSelect, adduser, adminpass, ADR, AES, AESGCM, afup, Afup, AFUP, Aga, aggration, Agilbee, agileparis, agiletour, agiletourparis, AgileTourParis, agilite, Agnès, ahk, airbnb, Airbnb, ajax, Akamai, Alamofire, AlamofireImage, alertMsg, Alexandre, algo, allSettled, ALors, alorscettearticle, amateure, Amélie, amelieboucher, Amongst, amoutte, amq, amqp, AMQP, AMQPConnection, amqplib, AMQPMessage, Anaïs, analytics, Andreosso, androïd, angularCLI, AngularCLI, AngularJs, AngularJS, AnnotationRegistry, anotherfe, ansur, AOT, APi, ApiBundle, ApiManager, APIs, apk, apks, apm, Apns, APNs, apollo, apolloJS, ApolloJS, apparait, apparaitre, Appbundle, AppBundle, AppCache, AppCompatActivity, AppData, AppEngine, Appfile, AppKernel, appli, applicationId, applicative, applicatives, applis, applyMiddleware, AprilKing, aps, ARANGO, args, ArgvInput, ARN, Arnaud, ArrayCollection, Arreter, ArticleControllerTest, ArticleListener, ArticleRepository, ArticleService, asc, asciinema, assertContains, assertEquals, assertInstanceOf, assertNotEmpty, assertTrue, Assetic, ast, AST, astonautes, AstronautController, AstronauteTests, astronautsKey, astronautsRepository, AstronautsRepository, async, Async, Asynctask, attachEvent, attemptReset, attrName, attrs, Aubervilliers, audras, Audras, auteure, auth, AuthGuard, AuthHttp, authHttpServiceFactory, autocomplete, autocomplétion, autoconfigure, AutoHotKey, autoload, autoloaded, autoloadés, autorized, autosquash, autowiring, AUTOWIRING, AvZNc, aws, AWS, axios, babelrc, BabylonJS, backend, Backend, BACKEND, backends, BackOffice, BackstopJs, backupGlobals, backupStaticAttributes, banniere, barAction, barButtonSystemItem, Barrista, barStyle, BaseBuilder, BaseClient, BaseConnection, BaseDocumentRepository, BaseExpr, baseurl, baseUrl, baseURL, BaseWebTestCase, bashrc, basicauth, baz, BDD, Bedford, beginTransaction, behat, Behat, BehatHTMLFormatter, BehatHTMLFormatterExtension, Belin, benevolat, benoit, beoneself, bétises, Bidelman, bidimensionnelles, bidirectionnalité, bientot, BigData, bindActionCreators, bindé, bindée, bindées, Bisounours, Bistri, BitBucket, Bithound, blackslash, bling, bloquage, bluetooth, bolognaise, bool, Bool, boolean, booleans, bootable, booter, bootloader, Bootloader, bordelique, botnet, Bouissou, BouteilleTest, brainstormer, Broutin, BrowserRouter, BSOD, BuildConfig, buildez, BuildFields, buildParameters, buildtype, buildType, buildTypes, BuildTypes, bundleName, bundler, byKeyPath, byProperty, cacheAction, cacheApp, cacheControl, cacheDir, cacheFirst, CacheInterface, CacheItem, callApi, callWebService, canActivate, caniuse, CannotPublishException, captainjojo, captainJojo, CarDetail, CarList, Carriou, Casabianca, CCMBenchmark, cd, CDD, celà, Cepedant, cer, certbot, Certbot, certonly, certSigningRequest, chaine, chainer, changeLabel, changeLanguage, changelog, chapo, charles, charset, chatbot, checkAndIncrease, checkCredentials, checkez, Cheric, ChericExampleBundle, Chet, chiffée, Chignet, ChildComponent, choo, choosen, Christophe, ciblée, circuitBreaker, CircuitBreaker, CircuitBreakerEvent, CircuitBreakerService, cksum, ClassLoader, classname, className, cleé, cli, Cli, CLI, Clickjacking, clientId, clipRect, cliquant, cliquer, Cliquer, cliquez, Cliquez, cloné, Clonez, CLose, ClosureExpressionBuilder, Clycks, ClycksBundle, ClycksClycksBundleController, ClycksController, cmd, Cmd, CNIL, coachs, Cocoapods, codeception, Codeception, Codelab, codelabs, Codelabs, CodeLabs, Codeship, codesigning, codestyling, Coffeescript, CoffeeScript, cogren, colorScheme, combineReducers, commandTester, CommandTester, commencant, commiter, CommitStrip, CommonJS, Communauty, compactée, complétement, complile, componentDidMount, componentDidUpdate, componentWillUnmount, ComposantEnfant, ComposantParent, Composieux, CompositeDisposable, concat, config, Config, CONFIG, configugarion, ConfigurationInterface, configurator, configureStore, configureUserInteractions, confs, connait, connaitre, conntrack, const, constraintlayout, ConstraintLayout, constraste, ContainerAware, ContainerAwareCommand, ContainerInterface, contentType, contextapi, ContextApi, ContextAPI, contributeur, controle, controlleur, convertErrorsToExceptions, convertNoticesToExceptions, convertWarningsToExceptions, coords, CoP, Copresence, Cordova, coredata, coreData, CoreData, coroutine, CoroutineLifeCycleListener, coroutines, correctServerQueryString, corresponddant, CouldNotCopyFileException, CounterActions, countFailure, countryOfOrigin, courrant, CQRS, createAnnotationMetadataConfiguration, createClient, createComponent, createContext, createdAt, createDir, createDraft, createElement, createFactory, createFromGlobals, createItem, createKernel, createQuery, createQueryBuilder, createSignalingChannel, createStore, creer, Creer, CRLF, cron, CRON, Crons, croped, crowdsourcer, cryptage, cryptanalysis, cryptographic, Cryptographic, cryptographiques, CSP, CSR, css, CSS, CSV, ctags, CTags, cto, CTO, ctrl, Ctrl, ctstate, cURL, customisés, CVAA, cy, Cybersécurité, da, d'a, d’Abstract, d'accélerer, d'acceptances, D'add, d'addon, d’Agilité, d’Amazon, damien, d'AMP, d'android, d'Android, d’Android, d'Angular, Dan's, d'ansible, d'Apache, d'API, d’API, d'Apollo, d'ApolloJS, d'app, Darkmira, Darricau, Dasini, DASINI, d'assets, DataFixtures, dataIdFromObject, dataItem, DataLayer, dataLayout, datamatrix, dataset, DataSource, dataType, datetime, DateTime, d'Atom, d'auth, dauthentification, d'autocomplétion, d'autoload, d'autoscalling, d’AWS, DBAL, dbd, DDD, ddos, DDR, débogage, débogueur, d’ebooks, debuggables, débugger, débuggeur, decache, décacher, d’ECMAscript, decrement, Decrement, DECREMENT, décrouvrons, dedeparisg, d'Edward, defaultConfig, DefaultController, defaultNS, défnir, déja, Delécolle, deleteDir, DeleteRealmIfMigrationNeeded, d'Eleven, d’Eleven, Delevery, Delrieu, d'emails, d’Emmanuelle, démo, DemoMyBundle, démos, d'émulateur, d'encrypter, Denos, dependancies, DependencyInjection, dépilement, déployables, dépot, Derussé, DERUSSÉ, d'ES, désalloué, DeSandro, Desbenoit, desc, descendEnBas, descripteurs, désélectionner, désérialisation, deserialize, désinscrites, désinstallation, désinstallé, Désinstaller, d'Eslint, dessend, destinaitaire, destructuring, désuette, desynchronization, detabinator, deuxieme, dev, Dev, dév, devbridge, developper, développeuse, développeuses, developpez, devfest, DevFest, DevFestNantes, devops, DevOps, devs, DevTools, d'éxecuter, d'éxécuter, d'execution, d'Expérience, d'export, dfce, d'helpers, d'HTTP, d’HTTP, DialoFlow, dialogflow, DialogFlow, d’IBM, d’ID, d'identifiant, didFailToRegisterForRemoteNotificationsWithError, didFinishLaunchingWithOptions, didReceiveRemoteNotification, didRegisterForRemoteNotificationsWithDeviceToken, d’ile, d’implémentation, d'implémentations, d'import, d’Infrastructure, d'instancier, d'integration, d’internet, d'Internet, d’Internet, d’interopérabilité, d'intéropérabilité, d’IOS, diposez, dir, dirname, disableOriginalConstructor, dispo, DistributionBundle, distros, DivisionByZeroException, Djavan, DLK, DLX, DMX, dns, DNS, d’Objective, docarticle, Dockerfile, dockerfiles, DockerHub, dockerisées, dockerremotephpdebugingexample, DockerRemotePhpDebugingExample, d'OCR, DocsPage, DoctrineBundle, DoctrineExtensionsBundle, DoctrineFixturesBundle, DocumentManager, documentName, DocumentRepository, d'ODM, d'Olivier, domotique, domotiques, doneButtonAction, doneToolbar, donut, Donut, d’opcode, d'OpenPGP, d'OpenSSL, doRequest, dotCSS, DotCSS, DotenvComponent, dotjs, dotJS, douverture, d'OVH, DPI, dport, dql, dreamteam, dsuarez, du [...]

2020-12-29 15:17 UTC, snroki commented on _layouts/post.html
> +            <a href="{{ tag | tag_url }}">
ça veut dire quoi ça ? Print tag ou tag_url ?

2020-12-29 15:19 UTC, snroki commented on _posts/en/2016-12-21-understanding-ssltls-part-1.md
> +**B - tls:**
mauvais remplacer je pense :p il était legit ce TLS

2020-12-29 15:20 UTC, snroki commented on _posts/fr/2016-04-22-kernel-terminate.md
> +    - notag
c'est vraiment utile ? Autant mettre symfony & php non ?

2020-12-29 15:21 UTC, snroki commented on _posts/fr/2016-06-21-git-rebase.md
> +tags: ['test']
c'est chelou non ? en tag on peut mettre git

2020-12-29 15:21 UTC, snroki commented on _posts/fr/2017-03-09-retour-experience-codeception.md
> +        - symfony:
mauvais remplacement !

2020-12-29 15:22 UTC, snroki commented on _posts/fr/2017-02-16-amelioration-continue-comment-animer-vos-retrospectives-agiles.md
>      - Amélioration continue
les 2 derniers tags sont pas bon non plus là, ils s'en est vraiment d'ailleurs ?

2020-12-29 15:22 UTC, snroki commented on _posts/fr/2017-12-13-comprendre-noyau-linux.md
> + - linux 4.9 (2016) contient environ 22 million de lignes de code pour 56 000 fichiers ;
le Linux est legit aussi

2020-12-29 15:22 UTC, snroki commented on _posts/fr/2018-03-28-gestion-d-environnement-avec-gradle.md
> +- android Studio
Android legit

2020-12-29 15:23 UTC, snroki commented on _posts/fr/2019-06-19-maba-gentle-force.md
> +    -
manque php

2020-12-29 15:24 UTC, snroki commented on _posts/fr/2020-09-30-meilleurs-outils-js-2020.md
> +    -  chrome
un espace en trop avant chrome

2020-12-29 15:55 UTC, Vik-Th0r commented on _layouts/post.html
> +            <a href="{{ tag | tag_url }}">
tag_url est un filtre tu lui donne un tag et lui se charge de te retourner son url ou sa symblink si dispo

2020-12-29 15:55 UTC, Vik-Th0r commented on _posts/en/2016-12-21-understanding-ssltls-part-1.md
> +**B - tls:**
bien vu

2020-12-29 15:57 UTC, Vik-Th0r commented on _posts/fr/2016-04-22-kernel-terminate.md
> +    - notag
ha ça c'était un test pour les article qui ne veule pas être référencé dans les vue tag
effectivement, je met php et symfo

2020-12-29 15:59 UTC, Vik-Th0r commented on _posts/fr/2016-06-21-git-rebase.md
> +tags: ['test']
oui pareil que celui d'avant

2020-12-29 16:01 UTC, Vik-Th0r commented on _posts/fr/2017-03-09-retour-experience-codeception.md
> +        - symfony:
mais quel oeil de faucon!

2020-12-29 16:03 UTC, Vik-Th0r commented on _posts/fr/2017-02-16-amelioration-continue-comment-animer-vos-retrospectives-agiles.md
>      - Amélioration continue
j'avoue ça craint, en plus ça crée des tag chelou et orphelin, je les supprime
Thomas va créer des règle pour les tags futures

2020-12-29 16:03 UTC, Vik-Th0r commented on _posts/fr/2017-12-13-comprendre-noyau-linux.md
> + - linux 4.9 (2016) contient environ 22 million de lignes de code pour 56 000 fichiers ;
bien vu

2020-12-29 16:04 UTC, Vik-Th0r commented on _posts/fr/2018-03-28-gestion-d-environnement-avec-gradle.md
> +- android Studio
yes

2020-12-29 16:05 UTC, Vik-Th0r commented on _posts/fr/2019-06-19-maba-gentle-force.md
> +    -
yes bien vu

2020-12-29 16:05 UTC, Vik-Th0r commented on _posts/fr/2020-09-30-meilleurs-outils-js-2020.md
> +    -  chrome
impec

2020-12-29 16:22 UTC, ElevenWilson commented
2699 words might be misspelled, please check them: aa, aandre, abd, Aboaf, Abramov, Abramov's, AbstractAdapter, AbstractController, accesseurs, AccountCanTransferMoney, ack, Ack, ACK, ACL, AComponent, acté, ActionTypes, activationCommands, addChild, addDecorator, addDoneButtonOnKeyboard, addEventListener, addGestureRecognizer, addkey, addListener, addon, Addon, addonlist, addons, Addons, addPlugin, addScore, addSelect, adduser, adminpass, ADR, AES, AESGCM, afup, Afup, AFUP, Aga, aggration, Agilbee, agileparis, agiletour, agiletourparis, AgileTourParis, agilite, Agnès, ahk, airbnb, Airbnb, ajax, Akamai, Alamofire, AlamofireImage, alertMsg, Alexandre, algo, allSettled, ALors, alorscettearticle, amateure, Amélie, amelieboucher, Amongst, amoutte, amq, amqp, AMQP, AMQPConnection, amqplib, AMQPMessage, Anaïs, analytics, Andreosso, androïd, angularCLI, AngularCLI, AngularJs, AngularJS, AnnotationRegistry, anotherfe, ansur, AOT, APi, ApiBundle, ApiManager, APIs, apk, apks, apm, Apns, APNs, apollo, apolloJS, ApolloJS, apparait, apparaitre, Appbundle, AppBundle, AppCache, AppCompatActivity, AppData, AppEngine, Appfile, AppKernel, appli, applicationId, applicative, applicatives, applis, applyMiddleware, AprilKing, aps, ARANGO, args, ArgvInput, ARN, Arnaud, ArrayCollection, Arreter, ArticleControllerTest, ArticleListener, ArticleRepository, ArticleService, asc, asciinema, assertContains, assertEquals, assertInstanceOf, assertNotEmpty, assertTrue, Assetic, ast, AST, astonautes, AstronautController, AstronauteTests, astronautsKey, astronautsRepository, AstronautsRepository, async, Async, Asynctask, attachEvent, attemptReset, attrName, attrs, Aubervilliers, audras, Audras, auteure, auth, AuthGuard, AuthHttp, authHttpServiceFactory, autocomplete, autocomplétion, autoconfigure, AutoHotKey, autoload, autoloaded, autoloadés, autorized, autosquash, autowiring, AUTOWIRING, AvZNc, aws, AWS, axios, babelrc, BabylonJS, backend, Backend, BACKEND, backends, BackOffice, BackstopJs, backupGlobals, backupStaticAttributes, banniere, barAction, barButtonSystemItem, Barrista, barStyle, BaseBuilder, BaseClient, BaseConnection, BaseDocumentRepository, BaseExpr, baseurl, baseUrl, baseURL, BaseWebTestCase, bashrc, basicauth, baz, BDD, Bedford, beginTransaction, behat, Behat, BehatHTMLFormatter, BehatHTMLFormatterExtension, Belin, benevolat, benoit, beoneself, Bidelman, bidimensionnelles, bidirectionnalité, bientot, BigData, bindActionCreators, bindé, bindée, bindées, Bisounours, Bistri, BitBucket, Bithound, blackslash, bling, bloquage, bluetooth, bolognaise, bool, Bool, boolean, booleans, bordelique, botnet, Bouissou, BouteilleTest, brainstormer, Broutin, BrowserRouter, BuildConfig, buildez, BuildFields, buildParameters, buildtype, buildType, buildTypes, BuildTypes, bundleName, bundler, byKeyPath, byProperty, cacheAction, cacheApp, cacheControl, cacheDir, cacheFirst, CacheInterface, CacheItem, callApi, callWebService, canActivate, caniuse, CannotPublishException, captainjojo, captainJojo, CarDetail, CarList, Carriou, Casabianca, CCMBenchmark, cd, CDD, Cepedant, cer, certbot, Certbot, certonly, certSigningRequest, chaine, chainer, changeLabel, changeLanguage, changelog, chapo, charles, charset, chatbot, checkAndIncrease, checkCredentials, checkez, Cheric, ChericExampleBundle, Chet, chiffée, Chignet, ChildComponent, choo, choosen, Christophe, ciblée, circuitBreaker, CircuitBreaker, CircuitBreakerEvent, CircuitBreakerService, cksum, ClassLoader, classname, className, cleé, cli, Cli, CLI, Clickjacking, clientId, clipRect, cliquant, cliquer, Cliquer, cliquez, Cliquez, cloné, Clonez, CLose, ClosureExpressionBuilder, Clycks, ClycksBundle, ClycksClycksBundleController, ClycksController, cmd, Cmd, CNIL, coachs, Cocoapods, codeception, Codeception, Codelab, codelabs, Codelabs, CodeLabs, Codeship, codesigning, codestyling, Coffeescript, CoffeeScript, cogren, colorScheme, combineReducers, commandTester, CommandTester, commencant, commiter, CommitStrip, CommonJS, Communauty, compactée, complétement, complile, componentDidMount, componentDidUpdate, componentWillUnmount, ComposantEnfant, ComposantParent, Composieux, CompositeDisposable, concat, config, Config, CONFIG, configugarion, ConfigurationInterface, configurator, configureStore, configureUserInteractions, confs, connait, connaitre, conntrack, const, constraintlayout, ConstraintLayout, constraste, ContainerAware, ContainerAwareCommand, ContainerInterface, contentType, contextapi, ContextApi, ContextAPI, contributeur, controle, controlleur, convertErrorsToExceptions, convertNoticesToExceptions, convertWarningsToExceptions, coords, CoP, Copresence, Cordova, coredata, coreData, CoreData, coroutine, CoroutineLifeCycleListener, coroutines, correctServerQueryString, corresponddant, CouldNotCopyFileException, CounterActions, countFailure, countryOfOrigin, courrant, CQRS, createAnnotationMetadataConfiguration, createClient, createComponent, createContext, createdAt, createDir, createDraft, createElement, createFactory, createFromGlobals, createItem, createKernel, createQuery, createQueryBuilder, createSignalingChannel, createStore, creer, Creer, CRLF, cron, CRON, Crons, croped, crowdsourcer, cryptage, cryptanalysis, cryptographic, Cryptographic, cryptographiques, CSP, CSR, css, CSS, CSV, ctags, CTags, cto, CTO, ctrl, Ctrl, ctstate, cURL, CVAA, cy, Cybersécurité, da, d'a, d’Abstract, d'accélerer, d'acceptances, D'add, d'addon, d’Agilité, d’Amazon, damien, d'AMP, d'android, d'Android, d’Android, d'Angular, Dan's, d'ansible, d'Apache, d'API, d’API, d'Apollo, d'ApolloJS, d'app, Darkmira, Darricau, Dasini, DASINI, d'assets, DataFixtures, dataIdFromObject, dataItem, DataLayer, dataLayout, datamatrix, dataset, DataSource, dataType, datetime, DateTime, d'Atom, d'auth, dauthentification, d'autocomplétion, d'autoload, d'autoscalling, d’AWS, DBAL, dbd, DDD, ddos, DDR, débogage, débogueur, d’ebooks, debuggables, débugger, débuggeur, decache, décacher, d’ECMAscript, decrement, Decrement, DECREMENT, décrouvrons, dedeparisg, d'Edward, defaultConfig, DefaultController, defaultNS, défnir, déja, Delécolle, deleteDir, DeleteRealmIfMigrationNeeded, d'Eleven, d’Eleven, Delevery, Delrieu, d'emails, d’Emmanuelle, démo, DemoMyBundle, démos, d'émulateur, d'encrypter, Denos, dependancies, DependencyInjection, dépilement, déployables, dépot, Derussé, DERUSSÉ, d'ES, désalloué, DeSandro, Desbenoit, desc, descendEnBas, descripteurs, désélectionner, désérialisation, deserialize, désinscrites, désinstallation, désinstallé, Désinstaller, d'Eslint, dessend, destinaitaire, destructuring, désuette, desynchronization, detabinator, deuxieme, dev, Dev, dév, devbridge, developper, développeuse, développeuses, developpez, devfest, DevFest, DevFestNantes, devops, DevOps, devs, DevTools, d'éxecuter, d'éxécuter, d'execution, d'Expérience, d'export, dfce, d'helpers, d'HTTP, d’HTTP, DialoFlow, dialogflow, DialogFlow, d’IBM, d’ID, d'identifiant, didFailToRegisterForRemoteNotificationsWithError, didFinishLaunchingWithOptions, didReceiveRemoteNotification, didRegisterForRemoteNotificationsWithDeviceToken, d’ile, d’implémentation, d'implémentations, d'import, d’Infrastructure, d'instancier, d'integration, d’internet, d'Internet, d’Internet, d’interopérabilité, d'intéropérabilité, d’IOS, diposez, dir, dirname, disableOriginalConstructor, dispo, DistributionBundle, distros, DivisionByZeroException, Djavan, DLK, DLX, DMX, dns, DNS, d’Objective, docarticle, Dockerfile, dockerfiles, DockerHub, dockerisées, dockerremotephpdebugingexample, DockerRemotePhpDebugingExample, d'OCR, DocsPage, DoctrineBundle, DoctrineExtensionsBundle, DoctrineFixturesBundle, DocumentManager, documentName, DocumentRepository, d'ODM, d'Olivier, domotique, domotiques, doneButtonAction, doneToolbar, donut, Donut, d’opcode, d'OpenPGP, d'OpenSSL, doRequest, dotCSS, DotCSS, DotenvComponent, dotjs, dotJS, douverture, d'OVH, DPI, dport, dql, dreamteam, dsuarez, d'Ubuntu, dûe, d'ui, d'UI, dumbledore, dunglas, Dunglas, DUNGLAS, d'Unicode,  [...]

2021-01-04 13:45 UTC, guillemcanal commented on _includes/main.scss
> +@import 'objects/chips';
@Vik-Th0r chips ?

2021-01-04 13:45 UTC, guillemcanal commented on _posts/en/2020-05-06-php-serverless-part-1.md
> +>>>>>>> origin/master
@Vik-Th0r Attention à ne pas commit un diff :)

2021-01-04 13:45 UTC, guillemcanal commented on _sass/objects/_chips.scss
> +.mdc-chip {
@Vik-Th0r C'est quoi un chip ?

2021-01-04 13:47 UTC, guillemcanal commented on feed.xml
> +        <description>{{ post.excerpt | xml_escape }}</description>
Je préfèrerai inclure la totalité de l'article dans nos flux, pensons aux gens qui utilisent Feedly :) Vous en pensez quoi ?

2021-01-04 13:48 UTC, VEBERArnaud requested changes
probleme de rebase dans ces fichiers

- `_posts/fr/2016-06-21-git-rebase.md`
- `_posts/en/2020-05-06-php-serverless-part-1.md`

2021-01-04 13:54 UTC, guillemcanal commented on feed.xml
> +        <description>{{ post.excerpt | xml_escape }}</description>
Peut-on garder l'intégralité de l'article pour les gens qui consomment le flux via Feedly ou autres ?

Après,  je comprends d'une certaine façon la modif, je suis plus habitué au format ATOM , qui est beaucoup plus explicite pour le contenu d'un article car ce dernier propose `summary` et `content` alors que RSS 2.0 ne propose que `description`  pour le contenu.

2021-01-04 15:27 UTC, Vik-Th0r commented on _includes/main.scss
> +@import 'objects/chips';
oui c'est ce genre de truc https://material-components.github.io/material-components-web-catalog/#/component/chips

2021-01-04 15:27 UTC, Vik-Th0r commented on _posts/en/2020-05-06-php-serverless-part-1.md
> +>>>>>>> origin/master
bien vu, un rebse assez cahotique

2021-01-04 15:32 UTC, Vik-Th0r commented on feed.xml
> +        <description>{{ post.excerpt | xml_escape }}</description>
bah pour moi c'est une erreur, le tag description ne doit pas retourner tout le contenu de l'article, le flux rss est sensé pouvoir donnée uniquement le lien vers les article en question, sinon ça niquerai les stats du site, non?

2021-01-04 15:33 UTC, Vik-Th0r commented on feed.xml
> +        <description>{{ post.excerpt | xml_escape }}</description>
après ça ne me dérange absolument pas de remettre content la dedans  mais ça me fait pas un tiquer :D

2021-01-04 15:41 UTC, guillemcanal commented on feed.xml
> +        <description>{{ post.excerpt | xml_escape }}</description>
je comprends @Vik-Th0r. Personnellement, quand un site ne propose pas l'intégralité de l'article dans le flux RSS/ATOM, je suis un peu colère. Vous en pensez quoi les autres ? @snroki (grand consommateur de flux devant l'éternel) ?

2021-01-04 15:42 UTC, guillemcanal approved these changes
Mis à part la partie sur le flux RSS (pas bloquant pour moi non plus), c'est tip top, merci @Vik-Th0r

2021-01-05 08:14 UTC, snroki commented on feed.xml
> +        <description>{{ post.excerpt | xml_escape }}</description>
bonsoir ! J'avoue que je suis de l'avis de @guillemcanal le flux rss doit représenter l'article IMO, après oui y'a une chance que la personne la lise depuis son lecteur et pas depuis le blog mais bon est-ce vraiment grave ? S'pas comme si on était payé par page vue haha, du moment que les gens lisent notre contenu et qu'ils nous connaissent c'est le principal non ? :)

2021-01-05 11:10 UTC, VEBERArnaud commented
je viens de push force pour faire le rebase master

2021-01-05 11:23 UTC, ElevenWilson commented
2654 words might be misspelled, please check them: aa, aandre, abd, Aboaf, Abramov, Abramov's, AbstractAdapter, accesseurs, AccountCanTransferMoney, ack, Ack, ACK, ACL, AComponent, acté, ActionTypes, activationCommands, addChild, addDecorator, addDoneButtonOnKeyboard, addEventListener, addGestureRecognizer, addkey, addListener, addon, Addon, addonlist, addons, Addons, addPlugin, addScore, addSelect, adduser, adminpass, ADR, AES, AESGCM, afup, Afup, AFUP, Aga, aggration, Agilbee, agileparis, agiletour, agiletourparis, AgileTourParis, agilite, Agnès, ahk, airbnb, Airbnb, ajax, Akamai, Alamofire, AlamofireImage, alertMsg, algo, allSettled, ALors, alorscettearticle, amateure, Amélie, amelieboucher, Amongst, amoutte, amq, amqp, AMQP, AMQPConnection, amqplib, AMQPMessage, Anaïs, analytics, Andreosso, androïd, angularCLI, AngularCLI, AngularJs, AngularJS, AnnotationRegistry, anotherfe, ansur, AOT, APi, ApiBundle, ApiManager, APIs, apk, apks, apm, Apns, APNs, apollo, apolloJS, ApolloJS, apparait, apparaitre, Appbundle, AppBundle, AppCache, AppCompatActivity, AppData, AppEngine, Appfile, AppKernel, appli, applicationId, applicative, applicatives, applis, applyMiddleware, AprilKing, aps, ARANGO, args, ArgvInput, ARN, Arnaud, Arreter, ArticleControllerTest, ArticleListener, ArticleRepository, ArticleService, asc, asciinema, assertContains, assertEquals, assertInstanceOf, assertNotEmpty, assertTrue, Assetic, ast, AST, astonautes, AstronauteTests, astronautsKey, async, Async, Asynctask, attachEvent, attemptReset, attrName, attrs, Aubervilliers, audras, Audras, auteure, auth, AuthGuard, AuthHttp, authHttpServiceFactory, autocomplete, autocomplétion, autoconfigure, AutoHotKey, autoload, autoloaded, autoloadés, autorized, autosquash, autowiring, AUTOWIRING, AvZNc, aws, AWS, axios, babelrc, BabylonJS, backend, Backend, BACKEND, backends, BackOffice, BackstopJs, backupGlobals, backupStaticAttributes, banniere, barAction, barButtonSystemItem, Barrista, barStyle, BaseBuilder, BaseClient, BaseConnection, BaseDocumentRepository, BaseExpr, baseurl, baseUrl, baseURL, BaseWebTestCase, bashrc, basicauth, baz, BDD, Bedford, beginTransaction, behat, Behat, BehatHTMLFormatter, BehatHTMLFormatterExtension, Belin, benevolat, benoit, beoneself, Bidelman, bidimensionnelles, bidirectionnalité, bientot, BigData, bindActionCreators, bindé, bindée, bindées, Bisounours, Bistri, BitBucket, Bithound, blackslash, bling, bloquage, bluetooth, bolognaise, bool, Bool, boolean, booleans, bordelique, botnet, Bouissou, BouteilleTest, brainstormer, Broutin, BrowserRouter, BuildConfig, buildez, BuildFields, buildParameters, buildtype, buildType, buildTypes, BuildTypes, bundleName, bundler, byKeyPath, byProperty, cacheAction, cacheApp, cacheControl, cacheDir, cacheFirst, CacheInterface, CacheItem, callApi, callWebService, canActivate, caniuse, CannotPublishException, captainjojo, captainJojo, CarDetail, CarList, Carriou, Casabianca, CCMBenchmark, cd, CDD, Cepedant, cer, certbot, Certbot, certonly, certSigningRequest, chaine, chainer, changeLabel, changeLanguage, changelog, chapo, charles, charset, chatbot, checkAndIncrease, checkCredentials, checkez, Cheric, ChericExampleBundle, Chet, chiffée, Chignet, ChildComponent, choo, choosen, Christophe, ciblée, circuitBreaker, CircuitBreaker, CircuitBreakerEvent, CircuitBreakerService, cksum, ClassLoader, classname, className, cleé, cli, Cli, CLI, Clickjacking, clientId, clipRect, cliquant, cliquer, Cliquer, cliquez, Cliquez, cloné, Clonez, CLose, Clycks, ClycksBundle, ClycksClycksBundleController, ClycksController, cmd, Cmd, CNIL, coachs, Cocoapods, codeception, Codeception, Codelab, codelabs, Codelabs, CodeLabs, Codeship, codesigning, codestyling, Coffeescript, CoffeeScript, cogren, colorScheme, combineReducers, commandTester, CommandTester, commencant, commiter, CommitStrip, CommonJS, Communauty, compactée, complétement, complile, componentDidMount, componentDidUpdate, componentWillUnmount, ComposantEnfant, ComposantParent, Composieux, CompositeDisposable, concat, config, Config, CONFIG, configugarion, ConfigurationInterface, configurator, configureStore, configureUserInteractions, confs, connait, connaitre, conntrack, const, constraintlayout, ConstraintLayout, constraste, ContainerAware, ContainerAwareCommand, ContainerInterface, contentType, contextapi, ContextApi, ContextAPI, contributeur, controle, controlleur, convertErrorsToExceptions, convertNoticesToExceptions, convertWarningsToExceptions, coords, CoP, Copresence, Cordova, coredata, coreData, CoreData, coroutine, CoroutineLifeCycleListener, coroutines, corresponddant, CouldNotCopyFileException, CounterActions, countFailure, countryOfOrigin, courrant, CQRS, createClient, createComponent, createContext, createdAt, createDir, createDraft, createElement, createFactory, createFromGlobals, createItem, createKernel, createQuery, createQueryBuilder, createSignalingChannel, createStore, creer, Creer, CRLF, cron, CRON, Crons, croped, crowdsourcer, cryptage, cryptanalysis, cryptographic, Cryptographic, cryptographiques, CSP, CSR, css, CSS, CSV, ctags, CTags, cto, CTO, ctrl, Ctrl, ctstate, cURL, CVAA, cy, Cybersécurité, da, d'a, d’Abstract, d'accélerer, d'acceptances, D'add, d'addon, d’Agilité, d’Amazon, damien, d'AMP, d'android, d'Android, d’Android, d'Angular, Dan's, d'ansible, d'Apache, d'API, d’API, d'Apollo, d'ApolloJS, d'app, Darkmira, Darricau, Dasini, DASINI, d'assets, DataFixtures, dataIdFromObject, dataItem, DataLayer, dataLayout, datamatrix, DataSource, dataType, datetime, DateTime, d'Atom, d'auth, dauthentification, d'autocomplétion, d'autoload, d'autoscalling, d’AWS, DBAL, dbd, DDD, ddos, DDR, débogage, débogueur, d’ebooks, debuggables, débugger, débuggeur, decache, décacher, d’ECMAscript, decrement, Decrement, DECREMENT, décrouvrons, dedeparisg, d'Edward, defaultConfig, DefaultController, defaultNS, défnir, déja, Delécolle, deleteDir, DeleteRealmIfMigrationNeeded, d'Eleven, d’Eleven, Delevery, Delrieu, d'emails, d’Emmanuelle, démo, DemoMyBundle, démos, d'émulateur, d'encrypter, Denos, dependancies, DependencyInjection, dépilement, déployables, dépot, Derussé, DERUSSÉ, d'ES, désalloué, DeSandro, Desbenoit, desc, descendEnBas, descripteurs, désélectionner, désérialisation, deserialize, désinscrites, désinstallation, désinstallé, Désinstaller, d'Eslint, dessend, destinaitaire, destructuring, désuette, desynchronization, detabinator, deuxieme, dev, Dev, dév, devbridge, developper, développeuse, développeuses, developpez, devfest, DevFest, DevFestNantes, devops, DevOps, devs, DevTools, d'éxecuter, d'éxécuter, d'execution, d'Expérience, d'export, dfce, d'helpers, d'HTTP, d’HTTP, DialoFlow, dialogflow, DialogFlow, d’IBM, d’ID, d'identifiant, didFailToRegisterForRemoteNotificationsWithError, didFinishLaunchingWithOptions, didReceiveRemoteNotification, didRegisterForRemoteNotificationsWithDeviceToken, d’ile, d’implémentation, d'implémentations, d'import, d’Infrastructure, d'instancier, d'integration, d’internet, d'Internet, d’Internet, d’interopérabilité, d'intéropérabilité, d’IOS, diposez, dir, dirname, disableOriginalConstructor, dispo, DistributionBundle, distros, DivisionByZeroException, Djavan, DLK, DLX, DMX, dns, DNS, d’Objective, docarticle, Dockerfile, dockerfiles, DockerHub, dockerisées, dockerremotephpdebugingexample, DockerRemotePhpDebugingExample, d'OCR, DocsPage, DoctrineBundle, DoctrineExtensionsBundle, DoctrineFixturesBundle, DocumentManager, documentName, DocumentRepository, d'ODM, d'Olivier, domotique, domotiques, doneButtonAction, doneToolbar, donut, d’opcode, d'OpenPGP, d'OpenSSL, doRequest, dotCSS, DotCSS, DotenvComponent, dotjs, dotJS, douverture, d'OVH, DPI, dport, dql, dreamteam, dsuarez, d'Ubuntu, dûe, d'ui, d'UI, dumbledore, dunglas, Dunglas, DUNGLAS, d'Unicode, d’update, d'upgrades, Dupire, d'url, d'URL, d’UX, eal, EasyAdminBundle, easybutton, easyButton, EasyRTC, EB, ECDSA, ecf, ecmascript, ecole, Ecole, EcoleRepository, Ecriture, EDH, edito, editorconfig, Editorconfig, Edouar [...]

2021-01-05 11:51 UTC, VEBERArnaud commented on _i18n/fr.yml
> +  tag_cloud: Tout les tags disponibles sur le blog
```suggestion
  tag_cloud: Tous les tags disponibles sur le blog
```

2021-01-05 11:52 UTC, VEBERArnaud commented on _includes/head.html
> +    <link rel="stylesheet" href="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css">
on est sur de vouloir la version latest ?
ca serait plus secure de pin une version en particulier

2021-01-05 11:53 UTC, VEBERArnaud commented on _includes/scripts.html
> +<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
déjà importé dans `_includes/head.html`

2021-01-05 12:59 UTC, Vik-Th0r commented on feed.xml
> +        <description>{{ post.excerpt | xml_escape }}</description>
ok comme vous voulez

2021-01-05 13:01 UTC, Vik-Th0r commented on feed.xml
> +        <description>{{ post.excerpt | xml_escape }}</description>
je le fais mais je me sens sale =D

2021-01-05 13:02 UTC, Vik-Th0r commented on _i18n/fr.yml
> +  tag_cloud: Tout les tags disponibles sur le blog
yes bien vu

2021-01-05 13:08 UTC, Vik-Th0r commented on _includes/scripts.html
> +<script src="https://unpkg.com/material-components-web@latest/dist/material-components-web.min.js"></script>
ok je les lock à la deniere v9.0.0

2021-01-05 13:24 UTC, ElevenWilson commented
2697 words might be misspelled, please check them: aa, aandre, abd, Aboaf, Abramov, Abramov's, AbstractAdapter, AbstractController, accesseurs, AccountCanTransferMoney, ack, Ack, ACK, ACL, AComponent, acté, ActionTypes, activationCommands, addChild, addDecorator, addDoneButtonOnKeyboard, addEventListener, addGestureRecognizer, addkey, addListener, addon, Addon, addonlist, addons, Addons, addPlugin, addScore, addSelect, adduser, adminpass, ADR, AES, AESGCM, afup, Afup, AFUP, Aga, aggration, Agilbee, agileparis, agiletour, agiletourparis, AgileTourParis, agilite, Agnès, ahk, airbnb, Airbnb, ajax, Akamai, Alamofire, AlamofireImage, alertMsg, Alexandre, algo, allSettled, ALors, alorscettearticle, amateure, Amélie, amelieboucher, Amongst, amoutte, amq, amqp, AMQP, AMQPConnection, amqplib, AMQPMessage, Anaïs, analytics, Andreosso, androïd, angularCLI, AngularCLI, AngularJs, AngularJS, AnnotationRegistry, anotherfe, ansur, AOT, APi, ApiBundle, ApiManager, APIs, apk, apks, apm, Apns, APNs, apollo, apolloJS, ApolloJS, apparait, apparaitre, Appbundle, AppBundle, AppCache, AppCompatActivity, AppData, AppEngine, Appfile, AppKernel, appli, applicationId, applicative, applicatives, applis, applyMiddleware, AprilKing, aps, ARANGO, args, ArgvInput, ARN, Arnaud, ArrayCollection, Arreter, ArticleControllerTest, ArticleListener, ArticleRepository, ArticleService, asc, asciinema, assertContains, assertEquals, assertInstanceOf, assertNotEmpty, assertTrue, Assetic, ast, AST, astonautes, AstronautController, AstronauteTests, astronautsKey, astronautsRepository, AstronautsRepository, async, Async, Asynctask, attachEvent, attemptReset, attrName, attrs, Aubervilliers, audras, Audras, auteure, auth, AuthGuard, AuthHttp, authHttpServiceFactory, autocomplete, autocomplétion, autoconfigure, AutoHotKey, autoload, autoloaded, autoloadés, autorized, autosquash, autowiring, AUTOWIRING, AvZNc, aws, AWS, axios, babelrc, BabylonJS, backend, Backend, BACKEND, backends, BackOffice, BackstopJs, backupGlobals, backupStaticAttributes, banniere, barAction, barButtonSystemItem, Barrista, barStyle, BaseBuilder, BaseClient, BaseConnection, BaseDocumentRepository, BaseExpr, baseurl, baseUrl, baseURL, BaseWebTestCase, bashrc, basicauth, baz, BDD, Bedford, beginTransaction, behat, Behat, BehatHTMLFormatter, BehatHTMLFormatterExtension, Belin, benevolat, benoit, beoneself, Bidelman, bidimensionnelles, bidirectionnalité, bientot, BigData, bindActionCreators, bindé, bindée, bindées, Bisounours, Bistri, BitBucket, Bithound, blackslash, bling, bloquage, bluetooth, bolognaise, bool, Bool, boolean, booleans, bordelique, botnet, Bouissou, BouteilleTest, brainstormer, Broutin, BrowserRouter, BuildConfig, buildez, BuildFields, buildParameters, buildtype, buildType, buildTypes, BuildTypes, bundleName, bundler, byKeyPath, byProperty, cacheAction, cacheApp, cacheControl, cacheDir, cacheFirst, CacheInterface, CacheItem, callApi, callWebService, canActivate, caniuse, CannotPublishException, captainjojo, captainJojo, CarDetail, CarList, Carriou, Casabianca, CCMBenchmark, cd, CDD, Cepedant, cer, certbot, Certbot, certonly, certSigningRequest, chaine, chainer, changeLabel, changeLanguage, changelog, chapo, charles, charset, chatbot, checkAndIncrease, checkCredentials, checkez, Cheric, ChericExampleBundle, Chet, chiffée, Chignet, ChildComponent, choo, choosen, Christophe, ciblée, circuitBreaker, CircuitBreaker, CircuitBreakerEvent, CircuitBreakerService, cksum, ClassLoader, classname, className, cleé, cli, Cli, CLI, Clickjacking, clientId, clipRect, cliquant, cliquer, Cliquer, cliquez, Cliquez, cloné, Clonez, CLose, ClosureExpressionBuilder, Clycks, ClycksBundle, ClycksClycksBundleController, ClycksController, cmd, Cmd, CNIL, coachs, Cocoapods, codeception, Codeception, Codelab, codelabs, Codelabs, CodeLabs, Codeship, codesigning, codestyling, Coffeescript, CoffeeScript, cogren, colorScheme, combineReducers, commandTester, CommandTester, commencant, commiter, CommitStrip, CommonJS, Communauty, compactée, complétement, complile, componentDidMount, componentDidUpdate, componentWillUnmount, ComposantEnfant, ComposantParent, Composieux, CompositeDisposable, concat, config, Config, CONFIG, configugarion, ConfigurationInterface, configurator, configureStore, configureUserInteractions, confs, connait, connaitre, conntrack, const, constraintlayout, ConstraintLayout, constraste, ContainerAware, ContainerAwareCommand, ContainerInterface, contentType, contextapi, ContextApi, ContextAPI, contributeur, controle, controlleur, convertErrorsToExceptions, convertNoticesToExceptions, convertWarningsToExceptions, coords, CoP, Copresence, Cordova, coredata, coreData, CoreData, coroutine, CoroutineLifeCycleListener, coroutines, correctServerQueryString, corresponddant, CouldNotCopyFileException, CounterActions, countFailure, countryOfOrigin, courrant, CQRS, createAnnotationMetadataConfiguration, createClient, createComponent, createContext, createdAt, createDir, createDraft, createElement, createFactory, createFromGlobals, createItem, createKernel, createQuery, createQueryBuilder, createSignalingChannel, createStore, creer, Creer, CRLF, cron, CRON, Crons, croped, crowdsourcer, cryptage, cryptanalysis, cryptographic, Cryptographic, cryptographiques, CSP, CSR, css, CSS, CSV, ctags, CTags, cto, CTO, ctrl, Ctrl, ctstate, cURL, CVAA, cy, Cybersécurité, da, d'a, d’Abstract, d'accélerer, d'acceptances, D'add, d'addon, d’Agilité, d’Amazon, damien, d'AMP, d'android, d'Android, d’Android, d'Angular, Dan's, d'ansible, d'Apache, d'API, d’API, d'Apollo, d'ApolloJS, d'app, Darkmira, Darricau, Dasini, DASINI, d'assets, DataFixtures, dataIdFromObject, dataItem, DataLayer, dataLayout, datamatrix, dataset, DataSource, dataType, datetime, DateTime, d'Atom, d'auth, dauthentification, d'autocomplétion, d'autoload, d'autoscalling, d’AWS, DBAL, dbd, DDD, ddos, DDR, débogage, débogueur, d’ebooks, debuggables, débugger, débuggeur, decache, décacher, d’ECMAscript, decrement, Decrement, DECREMENT, décrouvrons, dedeparisg, d'Edward, defaultConfig, DefaultController, defaultNS, défnir, déja, Delécolle, deleteDir, DeleteRealmIfMigrationNeeded, d'Eleven, d’Eleven, Delevery, Delrieu, d'emails, d’Emmanuelle, démo, DemoMyBundle, démos, d'émulateur, d'encrypter, Denos, dependancies, DependencyInjection, dépilement, déployables, dépot, Derussé, DERUSSÉ, d'ES, désalloué, DeSandro, Desbenoit, desc, descendEnBas, descripteurs, désélectionner, désérialisation, deserialize, désinscrites, désinstallation, désinstallé, Désinstaller, d'Eslint, dessend, destinaitaire, destructuring, désuette, desynchronization, detabinator, deuxieme, dev, Dev, dév, devbridge, developper, développeuse, développeuses, developpez, devfest, DevFest, DevFestNantes, devops, DevOps, devs, DevTools, d'éxecuter, d'éxécuter, d'execution, d'Expérience, d'export, dfce, d'helpers, d'HTTP, d’HTTP, DialoFlow, dialogflow, DialogFlow, d’IBM, d’ID, d'identifiant, didFailToRegisterForRemoteNotificationsWithError, didFinishLaunchingWithOptions, didReceiveRemoteNotification, didRegisterForRemoteNotificationsWithDeviceToken, d’ile, d’implémentation, d'implémentations, d'import, d’Infrastructure, d'instancier, d'integration, d’internet, d'Internet, d’Internet, d’interopérabilité, d'intéropérabilité, d’IOS, diposez, dir, dirname, disableOriginalConstructor, dispo, DistributionBundle, distros, DivisionByZeroException, Djavan, DLK, DLX, DMX, dns, DNS, d’Objective, docarticle, Dockerfile, dockerfiles, DockerHub, dockerisées, dockerremotephpdebugingexample, DockerRemotePhpDebugingExample, d'OCR, DocsPage, DoctrineBundle, DoctrineExtensionsBundle, DoctrineFixturesBundle, DocumentManager, documentName, DocumentRepository, d'ODM, d'Olivier, domotique, domotiques, doneButtonAction, doneToolbar, donut, Donut, d’opcode, d'OpenPGP, d'OpenSSL, doRequest, dotCSS, DotCSS, DotenvComponent, dotjs, dotJS, douverture, d'OVH, DPI, dport, dql, dreamteam, dsuarez, d'Ubuntu, dûe, d'ui, d'UI, dumbledore, dunglas, Dunglas, DUNGLAS, d'Unicode,  [...]

2021-01-05 14:04 UTC, VEBERArnaud approved these changes
LGTM
🐫 💨

2021-01-05 14:06 UTC, ElevenWilson commented
2676 words might be misspelled, please check them: aa, aandre, abd, Aboaf, Abramov, Abramov's, AbstractAdapter, accesseurs, AccountCanTransferMoney, ack, Ack, ACK, ACL, AComponent, acté, ActionTypes, activationCommands, addChild, addDecorator, addDoneButtonOnKeyboard, addEventListener, addGestureRecognizer, addkey, addListener, addon, Addon, addonlist, addons, Addons, addPlugin, addScore, addSelect, adduser, adminpass, ADR, AES, AESGCM, afup, Afup, AFUP, Aga, aggration, Agilbee, agileparis, agiletour, agiletourparis, AgileTourParis, agilite, Agnès, ahk, airbnb, Airbnb, ajax, Akamai, Alamofire, AlamofireImage, alertMsg, algo, allSettled, ALors, alorscettearticle, amateure, Amélie, amelieboucher, Amongst, amoutte, amq, amqp, AMQP, AMQPConnection, amqplib, AMQPMessage, Anaïs, analytics, Andreosso, androïd, angularCLI, AngularCLI, AngularJs, AngularJS, AnnotationRegistry, anotherfe, ansur, AOT, APi, ApiBundle, ApiManager, APIs, apk, apks, apm, Apns, APNs, apollo, apolloJS, ApolloJS, apparait, apparaitre, Appbundle, AppBundle, AppCache, AppCompatActivity, AppData, AppEngine, Appfile, AppKernel, appli, applicationId, applicative, applicatives, applis, applyMiddleware, AprilKing, aps, ARANGO, args, ArgvInput, arn, ARN, Arnaud, Arreter, ArticleControllerTest, ArticleListener, ArticleRepository, ArticleService, asc, asciinema, assertContains, assertEquals, assertInstanceOf, assertNotEmpty, assertTrue, Assetic, ast, AST, astonautes, AstronauteTests, astronautsKey, async, Async, Asynctask, attachEvent, attemptReset, attrName, attrs, Aubervilliers, audras, Audras, auteure, auth, AuthGuard, AuthHttp, authHttpServiceFactory, autocomplete, autocomplétion, autoconfigure, AutoHotKey, autoload, autoloaded, autoloader, autoloadés, autorized, autosquash, autowiring, AUTOWIRING, AvZNc, aws, Aws, AWS, axios, babelrc, BabylonJS, backend, Backend, BACKEND, backends, BackOffice, BackstopJs, backupGlobals, backupStaticAttributes, banniere, barAction, barButtonSystemItem, Barrista, barStyle, BaseBuilder, BaseClient, BaseConnection, BaseDocumentRepository, BaseExpr, baseurl, baseUrl, baseURL, BaseWebTestCase, bashrc, basicauth, baz, BDD, Bedford, beginTransaction, behat, Behat, BehatHTMLFormatter, BehatHTMLFormatterExtension, Belin, benevolat, benoit, beoneself, Bidelman, bidimensionnelles, bidirectionnalité, bientot, BigData, bindActionCreators, bindé, bindée, bindées, Bisounours, Bistri, BitBucket, Bithound, blackslash, bling, bloquage, bluetooth, bolognaise, bool, Bool, boolean, booleans, bordelique, botnet, Bouissou, BouteilleTest, brainstormer, Broutin, BrowserRouter, BuildConfig, buildez, BuildFields, buildParameters, buildtype, buildType, buildTypes, BuildTypes, bundleName, bundler, byKeyPath, byProperty, cacheAction, cacheApp, cacheControl, cacheDir, cacheFirst, CacheInterface, CacheItem, callApi, callWebService, canActivate, caniuse, CannotPublishException, captainjojo, captainJojo, CarDetail, CarList, Carriou, Casabianca, CCMBenchmark, cd, CDD, Cepedant, cer, certbot, Certbot, certonly, certSigningRequest, chaine, chainer, changeLabel, changeLanguage, changelog, chapo, charles, charset, chatbot, checkAndIncrease, checkCredentials, checkez, Cheric, ChericExampleBundle, Chet, chiffée, Chignet, ChildComponent, choo, choosen, Christophe, ciblée, circuitBreaker, CircuitBreaker, CircuitBreakerEvent, CircuitBreakerService, cksum, ClassLoader, classname, className, cleé, cli, Cli, CLI, Clickjacking, clientId, clipRect, cliquant, cliquer, Cliquer, cliquez, Cliquez, cloné, Clonez, CLose, Clycks, ClycksBundle, ClycksClycksBundleController, ClycksController, cmd, Cmd, CNIL, coachs, Cocoapods, codeception, Codeception, Codelab, codelabs, Codelabs, CodeLabs, Codeship, codesigning, codestyling, Coffeescript, CoffeeScript, cogren, colorScheme, combineReducers, commandTester, CommandTester, commencant, commiter, CommitStrip, CommonJS, Communauty, compactée, complétement, complile, componentDidMount, componentDidUpdate, componentWillUnmount, ComposantEnfant, ComposantParent, Composieux, CompositeDisposable, concat, config, Config, CONFIG, configugarion, ConfigurationInterface, configurator, configureStore, configureUserInteractions, confs, connait, connaitre, conntrack, const, constraintlayout, ConstraintLayout, constraste, ContainerAware, ContainerAwareCommand, ContainerInterface, contentType, contextapi, ContextApi, ContextAPI, contributeur, controle, controlleur, convertErrorsToExceptions, convertNoticesToExceptions, convertWarningsToExceptions, coords, CoP, Copresence, Cordova, coredata, coreData, CoreData, coroutine, CoroutineLifeCycleListener, coroutines, corresponddant, CouldNotCopyFileException, CounterActions, countFailure, countryOfOrigin, courrant, CQRS, createClient, createComponent, createContext, createdAt, createDir, createDraft, createElement, createFactory, createFromGlobals, createItem, createKernel, createQuery, createQueryBuilder, createSignalingChannel, createStore, creer, Creer, CRLF, cron, CRON, Crons, croped, crowdsourcer, cryptage, cryptanalysis, cryptographic, Cryptographic, cryptographiques, CSP, CSR, css, CSS, CSV, ctags, CTags, cto, CTO, ctrl, Ctrl, ctstate, cURL, CVAA, cy, Cybersécurité, da, d'a, d’Abstract, d'accélerer, d'acceptances, D'add, d'addon, d’Agilité, d’Amazon, damien, d'AMP, d'android, d'Android, d’Android, d'Angular, Dan's, d'ansible, d'Apache, d'API, d’API, d'Apollo, d'ApolloJS, d'app, Darkmira, Darricau, Dasini, DASINI, d'assets, DataFixtures, dataIdFromObject, dataItem, DataLayer, dataLayout, datamatrix, DataSource, dataType, datetime, DateTime, d'Atom, d'auth, dauthentification, d'autocomplétion, d'autoload, d'autoscalling, d’AWS, DBAL, dbd, DDD, ddos, DDR, débogage, débogueur, d’ebooks, debuggables, débugger, débuggeur, decache, décacher, d’ECMAscript, decrement, Decrement, DECREMENT, décrouvrons, dedeparisg, d'Edward, defaultConfig, DefaultController, defaultNS, défnir, déja, Delécolle, deleteDir, DeleteRealmIfMigrationNeeded, d'Eleven, d’Eleven, Delevery, Delrieu, d'emails, d’Emmanuelle, démo, DemoMyBundle, démos, d'émulateur, d'encrypter, Denos, dependancies, DependencyInjection, dépilement, déployables, dépot, Derussé, DERUSSÉ, d'ES, désalloué, DeSandro, Desbenoit, desc, descendEnBas, descripteurs, désélectionner, désérialisation, deserialize, désinscrites, désinstallation, désinstallé, Désinstaller, d'Eslint, dessend, destinaitaire, destructuring, désuette, desynchronization, detabinator, deuxieme, dev, Dev, dév, devbridge, developper, développeuse, développeuses, developpez, devfest, DevFest, DevFestNantes, devops, DevOps, devs, DevTools, d'éxecuter, d'éxécuter, d'execution, d'Expérience, d'export, dfce, d'helpers, d'HTTP, d’HTTP, DialoFlow, dialogflow, DialogFlow, d’IBM, d’ID, d'identifiant, didFailToRegisterForRemoteNotificationsWithError, didFinishLaunchingWithOptions, didReceiveRemoteNotification, didRegisterForRemoteNotificationsWithDeviceToken, d’ile, d’implémentation, d'implémentations, d'import, d’Infrastructure, d'instancier, d'integration, d’internet, d'Internet, d’Internet, d’interopérabilité, d'intéropérabilité, d’IOS, diposez, dir, dirname, disableOriginalConstructor, dispo, DistributionBundle, distros, DivisionByZeroException, Djavan, DLK, DLX, DMX, dns, DNS, d’Objective, docarticle, Dockerfile, dockerfiles, DockerHub, dockerisées, dockerremotephpdebugingexample, DockerRemotePhpDebugingExample, d'OCR, DocsPage, DoctrineBundle, DoctrineExtensionsBundle, DoctrineFixturesBundle, DocumentManager, documentName, DocumentRepository, d'ODM, d'Olivier, domotique, domotiques, doneButtonAction, doneToolbar, donut, d’opcode, d'OpenPGP, d'OpenSSL, doRequest, dotCSS, DotCSS, DotenvComponent, dotjs, dotJS, douverture, d'OVH, DPI, dport, dql, dreamteam, dsuarez, d'Ubuntu, dûe, d'ui, d'UI, dumbledore, dunglas, Dunglas, DUNGLAS, d'Unicode, d’update, d'upgrades, Dupire, d'url, d'URL, d’UX, eal, EasyAdminBundle, easybutton, easyButton, EasyRTC, EB, ECDSA, ecf, ecmascript, ecole, Ecole, EcoleRepository, Ecriture, EDH, edito, editorconfig [...]

2021-01-06 10:25 UTC, ElevenWilson commented
2676 words might be misspelled, please check them: aa, aandre, abd, Aboaf, Abramov, Abramov's, AbstractAdapter, accesseurs, AccountCanTransferMoney, ack, Ack, ACK, ACL, AComponent, acté, ActionTypes, activationCommands, addChild, addDecorator, addDoneButtonOnKeyboard, addEventListener, addGestureRecognizer, addkey, addListener, addon, Addon, addonlist, addons, Addons, addPlugin, addScore, addSelect, adduser, adminpass, ADR, AES, AESGCM, afup, Afup, AFUP, Aga, aggration, Agilbee, agileparis, agiletour, agiletourparis, AgileTourParis, agilite, Agnès, ahk, airbnb, Airbnb, ajax, Akamai, Alamofire, AlamofireImage, alertMsg, algo, allSettled, ALors, alorscettearticle, amateure, Amélie, amelieboucher, Amongst, amoutte, amq, amqp, AMQP, AMQPConnection, amqplib, AMQPMessage, Anaïs, analytics, Andreosso, androïd, angularCLI, AngularCLI, AngularJs, AngularJS, AnnotationRegistry, anotherfe, ansur, AOT, APi, ApiBundle, ApiManager, APIs, apk, apks, apm, Apns, APNs, apollo, apolloJS, ApolloJS, apparait, apparaitre, Appbundle, AppBundle, AppCache, AppCompatActivity, AppData, AppEngine, Appfile, AppKernel, appli, applicationId, applicative, applicatives, applis, applyMiddleware, AprilKing, aps, ARANGO, args, ArgvInput, arn, ARN, Arnaud, Arreter, ArticleControllerTest, ArticleListener, ArticleRepository, ArticleService, asc, asciinema, assertContains, assertEquals, assertInstanceOf, assertNotEmpty, assertTrue, Assetic, ast, AST, astonautes, AstronauteTests, astronautsKey, async, Async, Asynctask, attachEvent, attemptReset, attrName, attrs, Aubervilliers, audras, Audras, auteure, auth, AuthGuard, AuthHttp, authHttpServiceFactory, autocomplete, autocomplétion, autoconfigure, AutoHotKey, autoload, autoloaded, autoloader, autoloadés, autorized, autosquash, autowiring, AUTOWIRING, AvZNc, aws, Aws, AWS, axios, babelrc, BabylonJS, backend, Backend, BACKEND, backends, BackOffice, BackstopJs, backupGlobals, backupStaticAttributes, banniere, barAction, barButtonSystemItem, Barrista, barStyle, BaseBuilder, BaseClient, BaseConnection, BaseDocumentRepository, BaseExpr, baseurl, baseUrl, baseURL, BaseWebTestCase, bashrc, basicauth, baz, BDD, Bedford, beginTransaction, behat, Behat, BehatHTMLFormatter, BehatHTMLFormatterExtension, Belin, benevolat, benoit, beoneself, Bidelman, bidimensionnelles, bidirectionnalité, bientot, BigData, bindActionCreators, bindé, bindée, bindées, Bisounours, Bistri, BitBucket, Bithound, blackslash, bling, bloquage, bluetooth, bolognaise, bool, Bool, boolean, booleans, bordelique, botnet, Bouissou, BouteilleTest, brainstormer, Broutin, BrowserRouter, BuildConfig, buildez, BuildFields, buildParameters, buildtype, buildType, buildTypes, BuildTypes, bundleName, bundler, byKeyPath, byProperty, cacheAction, cacheApp, cacheControl, cacheDir, cacheFirst, CacheInterface, CacheItem, callApi, callWebService, canActivate, caniuse, CannotPublishException, captainjojo, captainJojo, CarDetail, CarList, Carriou, Casabianca, CCMBenchmark, cd, CDD, Cepedant, cer, certbot, Certbot, certonly, certSigningRequest, chaine, chainer, changeLabel, changeLanguage, changelog, chapo, charles, charset, chatbot, checkAndIncrease, checkCredentials, checkez, Cheric, ChericExampleBundle, Chet, chiffée, Chignet, ChildComponent, choo, choosen, Christophe, ciblée, circuitBreaker, CircuitBreaker, CircuitBreakerEvent, CircuitBreakerService, cksum, ClassLoader, classname, className, cleé, cli, Cli, CLI, Clickjacking, clientId, clipRect, cliquant, cliquer, Cliquer, cliquez, Cliquez, cloné, Clonez, CLose, Clycks, ClycksBundle, ClycksClycksBundleController, ClycksController, cmd, Cmd, CNIL, coachs, Cocoapods, codeception, Codeception, Codelab, codelabs, Codelabs, CodeLabs, Codeship, codesigning, codestyling, Coffeescript, CoffeeScript, cogren, colorScheme, combineReducers, commandTester, CommandTester, commencant, commiter, CommitStrip, CommonJS, Communauty, compactée, complétement, complile, componentDidMount, componentDidUpdate, componentWillUnmount, ComposantEnfant, ComposantParent, Composieux, CompositeDisposable, concat, config, Config, CONFIG, configugarion, ConfigurationInterface, configurator, configureStore, configureUserInteractions, confs, connait, connaitre, conntrack, const, constraintlayout, ConstraintLayout, constraste, ContainerAware, ContainerAwareCommand, ContainerInterface, contentType, contextapi, ContextApi, ContextAPI, contributeur, controle, controlleur, convertErrorsToExceptions, convertNoticesToExceptions, convertWarningsToExceptions, coords, CoP, Copresence, Cordova, coredata, coreData, CoreData, coroutine, CoroutineLifeCycleListener, coroutines, corresponddant, CouldNotCopyFileException, CounterActions, countFailure, countryOfOrigin, courrant, CQRS, createClient, createComponent, createContext, createdAt, createDir, createDraft, createElement, createFactory, createFromGlobals, createItem, createKernel, createQuery, createQueryBuilder, createSignalingChannel, createStore, creer, Creer, CRLF, cron, CRON, Crons, croped, crowdsourcer, cryptage, cryptanalysis, cryptographic, Cryptographic, cryptographiques, CSP, CSR, css, CSS, CSV, ctags, CTags, cto, CTO, ctrl, Ctrl, ctstate, cURL, CVAA, cy, Cybersécurité, da, d'a, d’Abstract, d'accélerer, d'acceptances, D'add, d'addon, d’Agilité, d’Amazon, damien, d'AMP, d'android, d'Android, d’Android, d'Angular, Dan's, d'ansible, d'Apache, d'API, d’API, d'Apollo, d'ApolloJS, d'app, Darkmira, Darricau, Dasini, DASINI, d'assets, DataFixtures, dataIdFromObject, dataItem, DataLayer, dataLayout, datamatrix, DataSource, dataType, datetime, DateTime, d'Atom, d'auth, dauthentification, d'autocomplétion, d'autoload, d'autoscalling, d’AWS, DBAL, dbd, DDD, ddos, DDR, débogage, débogueur, d’ebooks, debuggables, débugger, débuggeur, decache, décacher, d’ECMAscript, decrement, Decrement, DECREMENT, décrouvrons, dedeparisg, d'Edward, defaultConfig, DefaultController, defaultNS, défnir, déja, Delécolle, deleteDir, DeleteRealmIfMigrationNeeded, d'Eleven, d’Eleven, Delevery, Delrieu, d'emails, d’Emmanuelle, démo, DemoMyBundle, démos, d'émulateur, d'encrypter, Denos, dependancies, DependencyInjection, dépilement, déployables, dépot, Derussé, DERUSSÉ, d'ES, désalloué, DeSandro, Desbenoit, desc, descendEnBas, descripteurs, désélectionner, désérialisation, deserialize, désinscrites, désinstallation, désinstallé, Désinstaller, d'Eslint, dessend, destinaitaire, destructuring, désuette, desynchronization, detabinator, deuxieme, dev, Dev, dév, devbridge, developper, développeuse, développeuses, developpez, devfest, DevFest, DevFestNantes, devops, DevOps, devs, DevTools, d'éxecuter, d'éxécuter, d'execution, d'Expérience, d'export, dfce, d'helpers, d'HTTP, d’HTTP, DialoFlow, dialogflow, DialogFlow, d’IBM, d’ID, d'identifiant, didFailToRegisterForRemoteNotificationsWithError, didFinishLaunchingWithOptions, didReceiveRemoteNotification, didRegisterForRemoteNotificationsWithDeviceToken, d’ile, d’implémentation, d'implémentations, d'import, d’Infrastructure, d'instancier, d'integration, d’internet, d'Internet, d’Internet, d’interopérabilité, d'intéropérabilité, d’IOS, diposez, dir, dirname, disableOriginalConstructor, dispo, DistributionBundle, distros, DivisionByZeroException, Djavan, DLK, DLX, DMX, dns, DNS, d’Objective, docarticle, Dockerfile, dockerfiles, DockerHub, dockerisées, dockerremotephpdebugingexample, DockerRemotePhpDebugingExample, d'OCR, DocsPage, DoctrineBundle, DoctrineExtensionsBundle, DoctrineFixturesBundle, DocumentManager, documentName, DocumentRepository, d'ODM, d'Olivier, domotique, domotiques, doneButtonAction, doneToolbar, donut, d’opcode, d'OpenPGP, d'OpenSSL, doRequest, dotCSS, DotCSS, DotenvComponent, dotjs, dotJS, douverture, d'OVH, DPI, dport, dql, dreamteam, dsuarez, d'Ubuntu, dûe, d'ui, d'UI, dumbledore, dunglas, Dunglas, DUNGLAS, d'Unicode, d’update, d'upgrades, Dupire, d'url, d'URL, d’UX, eal, EasyAdminBundle, easybutton, easyButton, EasyRTC, EB, ECDSA, ecf, ecmascript, ecole, Ecole, EcoleRepository, Ecriture, EDH, edito, editorconfig [...]

2021-01-06 10:49 UTC, merged