Create 2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
eleven-labs/blog.eleven-labs.com pull request #822
Opened 2021-04-20 08:23 UTC by Fverneuil

2021-04-20 08:25 UTC, ElevenWilson commented
19 words might be misspelled, please check them: appréhendable, cliquer, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, Florian, lang, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 08:37 UTC, Pouzor commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +    - Florian
florian sans Majuscule

2021-04-20 08:38 UTC, Pouzor commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +#### 1.  Définition
### ici non ?

2021-04-20 08:40 UTC, Pouzor commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +Comme Kara Pernice nous le montre, en majorité, les utilisateurs ne lisent pas l’ensemble d'un site web [(cliquer ici pour accéder à l’article)](https://www.nngroup.com/articles/layer-cake-pattern-sc
Je suis pas fan des (cliquer ici pour accéder à l’article), ca serait plus intéressant d'intégrer les liens dans l'article plus subtilement.

2021-04-20 09:09 UTC, ElevenWilson commented
19 words might be misspelled, please check them: appréhendable, cliquer, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, Florian, lang, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 09:11 UTC, ElevenWilson commented
19 words might be misspelled, please check them: appréhendable, cliquer, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, Florian, lang, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 09:28 UTC, ElevenWilson commented
29 words might be misspelled, please check them: appréhendable, baseurl, cliquer, Cliquer, cliquez, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, Florian, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 09:43 UTC, Fverneuil commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +    - Florian
Pris en compte

2021-04-20 09:43 UTC, Fverneuil commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +#### 1.  Définition
Effectivement, merci !

2021-04-20 09:43 UTC, Fverneuil commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +Comme Kara Pernice nous le montre, en majorité, les utilisateurs ne lisent pas l’ensemble d'un site web [(cliquer ici pour accéder à l’article)](https://www.nngroup.com/articles/layer-cake-pattern-sc
Oui, tu as raison j'ai modifié ces éléments pour les intégrer davantage dans le texte :)

2021-04-20 09:44 UTC, snroki requested changes

2021-04-20 09:44 UTC, snroki commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +title: 'UX Writing : Introduction et bonnes pratiques'
utilise des double quotes plutôt (guillemets)

2021-04-20 09:44 UTC, snroki commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +
sauts de lignes inutiles

2021-04-20 09:44 UTC, snroki commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +permalink: /fr/UX-Writing-:-Introduction-et-bonnes-pratiques/
j'suis pas sûr que ça soit une bonne idée de mettre les ":" dans l'url

2021-04-20 09:44 UTC, snroki commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +En 1974, Loftus et Palmer ont réalisé une expérience qui démontre l'importance du choix du mot [(cliquer ici pour accéder à l’article)](http://resource.download.wjec.co.uk.s3.amazonaws.com/vtc/2015-1
ça serait mieux de mettre le lien sur la partie du texte qui d'écrit l'article plutôt que le fameux "cliquez ici" non ?

2021-04-20 09:44 UTC, ElevenWilson commented
26 words might be misspelled, please check them: appréhendable, baseurl, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, florian, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 09:46 UTC, snroki requested changes

2021-04-20 09:46 UTC, snroki commented on _posts/fr/2021-04-21-UX-Writing-Introduction-et-bonnes-pratiques.md
> +    - florian
d'ailleurs ton nom d'auteur normalement c'est normalisé en première lettre de ton prénom puis ton nom de famille CF la MR d'arnaud pour t'ajouter en auteur : https://github.com/eleven-labs/blog.eleven-labs.com/pull/821 donc tu dois mettre "fverneuil"

2021-04-20 09:48 UTC, ElevenWilson commented
26 words might be misspelled, please check them: appréhendable, baseurl, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, fverneuil, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 09:59 UTC, snroki approved these changes

2021-04-20 10:02 UTC, ElevenWilson commented
27 words might be misspelled, please check them: appréhendable, baseurl, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, fverneuil, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Ligertwood, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 11:53 UTC, ElevenWilson commented
27 words might be misspelled, please check them: appréhendable, baseurl, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, fverneuil, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Ligertwood, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 11:55 UTC, ElevenWilson commented
27 words might be misspelled, please check them: appréhendable, baseurl, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, fverneuil, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Ligertwood, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 14:29 UTC, ElevenWilson commented
27 words might be misspelled, please check them: appréhendable, baseurl, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, fverneuil, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Ligertwood, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-20 14:32 UTC, ElevenWilson commented
27 words might be misspelled, please check them: appréhendable, baseurl, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, fverneuil, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Ligertwood, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-21 08:49 UTC, ElevenWilson commented
27 words might be misspelled, please check them: appréhendable, baseurl, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, fverneuil, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Ligertwood, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-21 09:09 UTC, ElevenWilson commented
27 words might be misspelled, please check them: appréhendable, baseurl, crashées, crasher, CTA, Deliveroo, d’Évaluation, feedbacks, fverneuil, IllustrationConcis, IllustrationHomogeneite, IllustrationMéthode, IllustrationOrdre, IllustrationSeparation, IllustrationTitre, IllustrationUXWriting, lang, Ligertwood, Loftus, l'UX, l’UX, L’UX, Morkes, Nielse, Pernice, png, UX

2021-04-21 09:17 UTC, merged