Build website with nextjs
eleven-labs/blog.eleven-labs.com pull request #875
Opened 2022-01-24 12:37 UTC by antoine-amara

A new article about NextJS basics. Why and How using NextJS to build your website.

2022-01-24 13:58 UTC, jb-berthet requested changes
Took a first look more to the form than the substance. I'll take another look on the substance later, trying to follow your tutorial 😊 

So cool to have a NextJS tutorial by the way 🚀

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +But this framework is for building a web application with some user interfaces. Why create a website with NextJS?
I don't understand the meaning of the "But" phrase here 🤔

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +## Why you should construct your website with NextJS
```suggestion
## Why you should build your website with NextJS
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +* install NextJS project:
I would delete this line as it sounds redundant with the previous one to me.
```suggestion
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +* Or clone the git repo example and checkout the get-started branch:
```suggestion
You can also clone the git repository of this tutorial:
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +
```suggestion
### Create the index page

To start, delete the `src/pages/index.js` content, to start from a blank page and not with the NextJS welcome page.
Now, we need to build our website layout, let's create a reusable React component and integrate it in the global NextJS App component to see it in each generated pages.

> **Note**: all website pages are in the `src/pages` folder.

```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +Now, just add the HTML content for the index page.
I had the feeling that I had to do this by myself, but that what you will explain in next part, am I wrong? :) 

```suggestion
Now, we will add the HTML content for the index page.
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +* Just add HTML content with a JSX template to have the page content:
Same as before, no need to start a list here 😉 

```suggestion
Just add HTML content with a JSX template to have the page content:
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +The index.js and Layout.js components contain redirections to other website pages, but they don't exist yet. Let's learn how to create these pages NextJS.
Some Markdown emphasis for file names. Can you also add the path of each file?

```suggestion
The `index.js` and `Layout.js` components contain redirections to other website pages, but they don't exist yet. Let's learn how to create these pages NextJS.
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +Now we have a contact page. The website needs one page for each astronaut's team. To do that, create a route with the team name as a parameter.
Same as before, I had the feeling that I had to do it by myself, although you're going to go through that after. I think it is clearer like this :)

```suggestion
Now we have a contact page, the website needs one page for each astronaut's team. To do that, we will create a route with the team name as a parameter.
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +Now we have a website ready to be published. Now, let's have a return of experience about building this website.
```suggestion
Now we have a website ready to be published. Now, let's sum up feedback about building this website.
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +## Return of experience
```suggestion
## Feedback
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +Let's see some comments about building this website example:
```suggestion
Here's what we learned building this small website:
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +* * Easy to init: the project is super easy to init with create-next-app and, it is ready to construct, build and deploy with any additional configurations.
```suggestion
* Easy to init: the project is super easy to init with create-next-app and is ready to be built and deployed without any additional configurations.
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +Comes with tooling: the project comes with some tooling like pre-configured Eslint configurations or some pre-configured npm scripts. The Eslint configuration can be better but, it is a good starting
```suggestion
* Comes with tooling: the project comes with some tooling like pre-configured Eslint configurations or some pre-configured npm scripts. The Eslint configuration can be better but, it is a good starting point.
```

2022-01-24 13:58 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +* React: It is easy to construct with the power of React components if you know it for sure. Moreover, you can construct a lot of reusable things across your website. Finally, if you need it, you can
I didn't say it before, but prefer using "build" over "construct" 

```suggestion
* React: It is easy to build with the power of React components if you know it. Moreover, you can build a lot of reusable things across your website. Finally, if you need it, you can also take some React components from npm and use them on your website.
```

2022-01-25 14:39 UTC, jb-berthet reviewed
Attention, tu mentionnes souvent le dossier `src` alors qu'il n'existe pas dans le projet. Tu peux parler de "root folder" ou un truc du genre à la place.

J'ai essayé de suivre le tuto sans cloner le repo dans un premier temps et c'est clairement pas possible car il y a plein de code qui me manque. En fait, comme tu montres comment créer une application next au début, je m'attendais à ce que ce soit possible de suivre tout from scratch 😕 Et puis si on fait pas from scratch et qu'on prend ton code finalement c'est plus un tuto, juste toi qui nous nous montre comment tu montes ton appli avec Next (si c'est le cas faut plutôt employer les formules du genre "je fais ci, puis je fais ça, parce que... 🙂)

Donc ce que tu peux faire c'est soit:
- Tu prends le truc en mode "je fais ci, je fais ça parce que..."
- Tu mets tout le code qu'il faut copier dans l'article, avec des bloc "collapsibles" par exemple (même si je pense que ça ferait beaucoup de code)
- Tu fais des branches avec le code de base que tu veux filer à chaque étape, comme une sorte d'évolution de l'appli en fonction de où tu en es dans le tuto
- Autre chose si tu trouves un bon moyen !

Dis moi si je vais trop loin dans le délire et que tu es pas d'accord avec ce que je remonte en tout cas, j'ai pas la science infuse, je partage juste mon ressenti et mon avis 😉 

P.S. : Très cool ce petit site des planètes mais t'aurais dû mettre une description moins impartiale pour les Schizos Cats, style "Beside the fact that they're not first in the planet race (for now), Schizos Cats are the best team of the Galaxy." 😛

2022-01-25 14:39 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +Let’s build a website about the astronauts' teams of eleven labs.
With capital letters because we're kings 👑 
```suggestion
Let’s build a website about the astronauts' teams of Eleven Labs.
```

2022-01-25 14:39 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +The `src/pages/index.js` and `src/components/Layout.js` components contain redirections to other website pages, but they don't exist yet. Let's learn how to create these pages NextJS.
typo
```suggestion
The `src/pages/index.js` and `src/components/Layout.js` components contain redirections to other website pages, but they don't exist yet. Let's learn how to create these pages with NextJS.
```

2022-01-25 14:39 UTC, jb-berthet commented on _posts/en/2022-01-26-build-website-with-nextjs.md
> +ere's what we learned building this small website:
typo
```suggestion
Here's what we learned building this small website:
```

2022-01-25 18:59 UTC, antoine-amara commented
@jb-berthet  ce que je peux faire c'est retirer la commande pour initialiser un projet vide et informer les lecteurs qu'il faut cloner le repo pour suivre. (je peux laisser la commande de creation de projet vide en note). J'explique que l'on va creer les pages et non le contenu du site en lui meme et que l'ensemble des composants utiles sont deja la (ce qui est le cas sur la branche `get-started`)

2022-01-25 21:04 UTC, jb-berthet commented
> @jb-berthet  ce que je peux faire c'est retirer la commande pour initialiser un projet vide et informer les lecteurs qu'il faut cloner le repo pour suivre. (je peux laisser la commande de creation de projet vide en note). J'explique que l'on va creer les pages et non le contenu du site en lui meme et que l'ensemble des composants utiles sont deja la (ce qui est le cas sur la branche `get-started`)

Ouais grave nikel ! En fait c'est carrément ça, si les fichiers sont pas montrés dans l'article il faut qu'ils soient dans le `get-started` (j'ai complètement loupé cette branche en fait, désolé 😕)

2022-01-31 09:35 UTC, antoine-amara commented
Due to an error about opening a PR from a fork, close this one and open an another one.

2022-01-31 09:35 UTC, closed without merging